EXPECTED = {'functions': {'dot': {'params': [('u', ('tensor', [('n', 'invariant')])),
                                  ('v', ('tensor', [('n', 'invariant')]))],
                       'return_type': 'ℝ',
                       'body': ('call',
                                'sum',
                                [('for_expr',
                                  'i',
                                  ('var', 'n'),
                                  ('mul',
                                   ('index', 'u', ('imaginary',)),
                                   ('index', 'v', ('imaginary',))))]),
                       'has_loop': False,
                       'statements': []},
               'append': {'params': [('u', ('tensor', [('n', 'invariant')])),
                                     ('v', 'ℝ')],
                          'return_type': ('tensor',
                                          [(('add_dim', 'n', 1), 'invariant')]),
                          'body': ('add',
                                   ('var', 'u'),
                                   ('array', [('var', 'v')])),
                          'has_loop': False,
                          'statements': []},
               'f': {'params': [('n', 'ℝ'),
                                ('v', ('tensor', [('m', 'invariant')]))],
                     'return_type': 'ℕ',
                     'body': ('var', 'm'),
                     'has_loop': False,
                     'statements': []},
               'outer3': {'params': [('u', ('tensor', [('m', 'invariant')])),
                                     ('v', ('tensor', [('n', 'invariant')])),
                                     ('w', ('tensor', [('p', 'invariant')]))],
                          'return_type': ('tensor',
                                          [('m', 'invariant'),
                                           ('n', 'invariant'),
                                           ('p', 'invariant')]),
                          'body': ('for_expr',
                                   'i',
                                   ('var', 'm'),
                                   ('for_expr',
                                    'j',
                                    ('var', 'n'),
                                    ('for_expr',
                                     'k',
                                     ('var', 'p'),
                                     ('mul',
                                      ('mul',
                                       ('index', 'u', ('imaginary',)),
                                       ('index', 'v', ('var', 'j'))),
                                      ('index', 'w', ('var', 'k')))))),
                          'has_loop': False,
                          'statements': []},
               'append_row': {'params': [('x',
                                          ('tensor',
                                           [('m', 'invariant'),
                                            ('n', 'invariant')])),
                                         ('row',
                                          ('tensor', [('n', 'invariant')]))],
                              'return_type': ('tensor',
                                              [(('add_dim', 'm', 1),
                                                'invariant'),
                                               ('n', 'invariant')]),
                              'body': ('add',
                                       ('var', 'x'),
                                       ('array', [('var', 'row')])),
                              'has_loop': False,
                              'statements': []}},
 'classes': {},
 'program': [('func_def', 'dot'),
             ('decl',
              'v3',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              9),
             ('decl',
              'w3',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 4.0), ('num', 5.0), ('num', 6.0)]),
              10),
             ('decl', 'e', 'ℝ', ('num', 3.0), 11),
             ('expr', ('call', 'dot', [('var', 'v3'), ('var', 'w3')]), 0),
             ('func_def', 'append'),
             ('expr', ('call', 'append', [('var', 'v3'), ('var', 'e')]), 0),
             ('expr',
              ('call',
               'append',
               [('call', 'append', [('var', 'v3'), ('var', 'e')]),
                ('var', 'e')]),
              0),
             ('func_def', 'f'),
             ('decl', 'a', 'ℝ', ('num', 5.0), 33),
             ('expr', ('call', 'f', [('var', 'a'), ('var', 'v3')]), 0),
             ('func_def', 'outer3'),
             ('expr',
              ('call',
               'outer3',
               [('var', 'v3'),
                ('array', [('num', 1.0), ('num', 0.0)]),
                ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)])]),
              0),
             ('func_def', 'append_row'),
             ('decl',
              'x2mat',
              ('tensor', [(3, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 3.0), ('num', 2.0)]),
                ('array', [('num', 1.0), ('num', 2.0)]),
                ('array', [('num', 1.0), ('num', 2.0)])]),
              49),
             ('decl',
              'new_row',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 1.0), ('num', 5.0)]),
              50),
             ('expr',
              ('call', 'append_row', [('var', 'x2mat'), ('var', 'new_row')]),
              0)]}
