EXPECTED = {'functions': {'slice_demo_1d': {'params': [('a',
                                             ('tensor', [('m', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('n', 'invariant')]),
                                 'body': ('indexN',
                                          'a',
                                          [('slice_item', None, ('num', 2))]),
                                 'has_loop': False,
                                 'statements': []},
               'slice_demo_2d': {'params': [('a',
                                             ('tensor',
                                              [('m', 'invariant'),
                                               ('n', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('o', 'invariant')]),
                                 'body': ('indexN',
                                          'a',
                                          [('slice_item', None, None),
                                           ('index_item', ('num', 0))]),
                                 'has_loop': False,
                                 'statements': []},
               'slice_demo_3d': {'params': [('a',
                                             ('tensor',
                                              [('m', 'invariant'),
                                               ('n', 'invariant'),
                                               ('o', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('p', 'invariant')]),
                                 'body': ('indexN',
                                          'a',
                                          [('slice_item', None, None),
                                           ('index_item', ('num', 0)),
                                           ('index_item', ('num', 0))]),
                                 'has_loop': False,
                                 'statements': []}},
 'classes': {'SliceDemo': {'class_params': [],
                           'fields': [],
                           'methods': [{'name': 'return_x',
                                        'params': [('x',
                                                    ('tensor',
                                                     [(8, 'invariant')]))],
                                        'return_type': ('tensor',
                                                        [('m', 'invariant')]),
                                        'statements': [],
                                        'body': ('indexN',
                                                 'x',
                                                 [('slice_item',
                                                   None,
                                                   ('num', 4))])},
                                       {'name': 'return_y',
                                        'params': [('y',
                                                    ('tensor',
                                                     [(4, 'invariant'),
                                                      (4, 'invariant')]))],
                                        'return_type': ('tensor',
                                                        [('n', 'invariant')]),
                                        'statements': [],
                                        'body': ('indexN',
                                                 'y',
                                                 [('slice_item', None, None),
                                                  ('index_item', ('num', 1))])},
                                       {'name': 'return_z',
                                        'params': [('z',
                                                    ('tensor',
                                                     [(2, 'invariant'),
                                                      (2, 'invariant'),
                                                      (2, 'invariant')]))],
                                        'return_type': ('tensor',
                                                        [('m', 'invariant')]),
                                        'statements': [],
                                        'body': ('indexN',
                                                 'z',
                                                 [('slice_item', None, None),
                                                  ('index_item', ('num', 1)),
                                                  ('index_item',
                                                   ('num', 0))])}]}},
 'program': [('decl',
              'x',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('num', 1),
                ('num', 2),
                ('num', 3),
                ('num', 4),
                ('num', 5),
                ('num', 6),
                ('num', 7),
                ('num', 8)]),
              21),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 3), ('num', 4)]),
                ('array', [('num', 5), ('num', 6), ('num', 7), ('num', 8)]),
                ('array', [('num', 9), ('num', 10), ('num', 11), ('num', 12)]),
                ('array',
                 [('num', 13), ('num', 14), ('num', 15), ('num', 16)])]),
              23),
             ('decl',
              'z',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1), ('num', 2)]),
                  ('array', [('num', 3), ('num', 4)])]),
                ('array',
                 [('array', [('num', 5), ('num', 6)]),
                  ('array', [('num', 7), ('num', 8)])])]),
              30),
             ('assign',
              'x_slice_1_to_3',
              ('indexN', 'x', [('slice_item', ('num', 1), ('num', 3))]),
              41),
             ('assign',
              'x_slice_start_to_4',
              ('indexN', 'x', [('slice_item', None, ('num', 4))]),
              42),
             ('assign',
              'y_rows_1_to_3',
              ('indexN',
               'y',
               [('slice_item', ('num', 1), ('num', 3)),
                ('slice_item', None, None)]),
              44),
             ('assign',
              'y_column_2',
              ('indexN',
               'y',
               [('slice_item', None, None), ('index_item', ('num', 2))]),
              45),
             ('assign',
              'z_layer_1',
              ('indexN',
               'z',
               [('index_item', ('num', 1)),
                ('slice_item', None, None),
                ('slice_item', None, None)]),
              47),
             ('assign',
              'z_first_element_each_layer',
              ('indexN',
               'z',
               [('slice_item', None, None),
                ('index_item', ('num', 0)),
                ('index_item', ('num', 0))]),
              48),
             ('expr', ('var', 'x_slice_1_to_3'), 0),
             ('expr', ('var', 'x_slice_start_to_4'), 0),
             ('expr', ('var', 'y_rows_1_to_3'), 0),
             ('expr', ('var', 'y_column_2'), 0),
             ('expr', ('var', 'z_layer_1'), 0),
             ('expr', ('var', 'z_first_element_each_layer'), 0),
             ('decl',
              'x',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('num', 1),
                ('num', 2),
                ('num', 3),
                ('num', 4),
                ('num', 5),
                ('num', 6),
                ('num', 7),
                ('num', 8)]),
              61),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 3), ('num', 4)]),
                ('array', [('num', 5), ('num', 6), ('num', 7), ('num', 8)]),
                ('array', [('num', 9), ('num', 10), ('num', 11), ('num', 12)]),
                ('array',
                 [('num', 13), ('num', 14), ('num', 15), ('num', 16)])]),
              63),
             ('decl',
              'z',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1), ('num', 2)]),
                  ('array', [('num', 3), ('num', 4)])]),
                ('array',
                 [('array', [('num', 5), ('num', 6)]),
                  ('array', [('num', 7), ('num', 8)])])]),
              70),
             ('func_def', 'slice_demo_1d'),
             ('func_def', 'slice_demo_2d'),
             ('func_def', 'slice_demo_3d'),
             ('decl',
              'func_x',
              ('tensor', [(8, 'invariant')]),
              ('call', 'slice_demo_1d', [('var', 'x')]),
              91),
             ('decl',
              'func_y',
              ('tensor', [(4, 'invariant')]),
              ('call', 'slice_demo_2d', [('var', 'y')]),
              92),
             ('decl',
              'func_z',
              ('tensor', [(2, 'invariant')]),
              ('call', 'slice_demo_3d', [('var', 'z')]),
              93),
             ('expr', ('var', 'func_x'), 0),
             ('expr', ('var', 'func_y'), 0),
             ('expr', ('var', 'func_z'), 0),
             ('decl',
              'x',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('num', 1),
                ('num', 2),
                ('num', 3),
                ('num', 4),
                ('num', 5),
                ('num', 6),
                ('num', 7),
                ('num', 8)]),
              106),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 3), ('num', 4)]),
                ('array', [('num', 5), ('num', 6), ('num', 7), ('num', 8)]),
                ('array', [('num', 9), ('num', 10), ('num', 11), ('num', 12)]),
                ('array',
                 [('num', 13), ('num', 14), ('num', 15), ('num', 16)])]),
              108),
             ('decl',
              'z',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1), ('num', 2)]),
                  ('array', [('num', 3), ('num', 4)])]),
                ('array',
                 [('array', [('num', 5), ('num', 6)]),
                  ('array', [('num', 7), ('num', 8)])])]),
              115),
             ('class_def', 'SliceDemo'),
             ('decl',
              'obj_slice_demo',
              ('struct_type', 'SliceDemo'),
              ('call', 'SliceDemo', []),
              134),
             ('assign',
              'class_x',
              ('method_call',
               ('var', 'obj_slice_demo'),
               'return_x',
               [('var', 'x')]),
              135),
             ('assign',
              'class_y',
              ('method_call',
               ('var', 'obj_slice_demo'),
               'return_y',
               [('var', 'y')]),
              136),
             ('assign',
              'class_z',
              ('method_call',
               ('var', 'obj_slice_demo'),
               'return_z',
               [('var', 'z')]),
              137),
             ('expr', ('var', 'class_x'), 0),
             ('expr', ('var', 'class_y'), 0),
             ('expr', ('var', 'class_z'), 0),
             ('decl',
              'x',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('num', 1),
                ('num', 2),
                ('num', 3),
                ('num', 4),
                ('num', 5),
                ('num', 6),
                ('num', 7),
                ('num', 8)]),
              148),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 3), ('num', 4)]),
                ('array', [('num', 5), ('num', 6), ('num', 7), ('num', 8)]),
                ('array', [('num', 9), ('num', 10), ('num', 11), ('num', 12)]),
                ('array',
                 [('num', 13), ('num', 14), ('num', 15), ('num', 16)])]),
              150),
             ('decl',
              'z',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1), ('num', 2)]),
                  ('array', [('num', 3), ('num', 4)])]),
                ('array',
                 [('array', [('num', 5), ('num', 6)]),
                  ('array', [('num', 7), ('num', 8)])])]),
              157),
             ('decl',
              'x_assign',
              ('tensor', [(8, 'invariant')]),
              ('var', 'x'),
              168),
             ('decl',
              'y_assign',
              ('tensor', [(4, 'invariant'), (4, 'invariant')]),
              ('var', 'y'),
              169),
             ('decl',
              'z_assign',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (2, 'invariant')]),
              ('var', 'z'),
              170),
             ('index_assign_nd',
              'x_assign',
              [('slice_item', ('num', 1), ('num', 3))],
              ('array', [('num', 10), ('num', 20)]),
              172),
             ('index_assign_nd',
              'y_assign',
              [('slice_item', None, None), ('index_item', ('num', 0))],
              ('array', [('num', 10), ('num', 20), ('num', 30), ('num', 40)]),
              173),
             ('index_assign_nd',
              'z_assign',
              [('slice_item', None, None),
               ('slice_item', None, None),
               ('index_item', ('num', 0))],
              ('array', [('num', 10), ('num', 20)]),
              174),
             ('expr', ('var', 'x_assign'), 0),
             ('expr', ('var', 'y_assign'), 0),
             ('expr', ('var', 'z_assign'), 0),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 3), ('num', 4)]),
                ('array', [('num', 5), ('num', 6), ('num', 7), ('num', 8)]),
                ('array', [('num', 9), ('num', 10), ('num', 11), ('num', 12)]),
                ('array',
                 [('num', 13), ('num', 14), ('num', 15), ('num', 16)])]),
              186),
             ('decl',
              'z',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1), ('num', 2)]),
                  ('array', [('num', 3), ('num', 4)])]),
                ('array',
                 [('array', [('num', 5), ('num', 6)]),
                  ('array', [('num', 7), ('num', 8)])])]),
              193),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('num', 2),
              [('for_index_assign_nd',
                'y',
                [('slice_item', None, None), ('index_item', ('num', 0))],
                ('array', [('num', 1), ('num', 2), ('num', 3), ('num', 4)]))],
              204),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('num', 2),
              [('for_index_assign_nd',
                'z',
                [('slice_item', None, None),
                 ('index_item', ('num', 0)),
                 ('index_item', ('num', 0))],
                ('array', [('num', 9), ('num', 10)]))],
              208),
             ('decl',
              'loop_y',
              ('tensor', [(4, 'invariant'), (4, 'invariant')]),
              ('var', 'y'),
              211),
             ('decl',
              'loop_z',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (2, 'invariant')]),
              ('var', 'z'),
              212),
             ('expr', ('var', 'loop_y'), 0),
             ('expr', ('var', 'loop_z'), 0)]}
