EXPECTED = {'functions': {},
 'classes': {},
 'program': [('unit_decl', 'm', 'ℝ', [('kg', 1)], ('num', 5.0), 11),
             ('unit_decl', 'a', 'ℝ', [('m', 1), ('s', -2)], ('num', 2.0), 12),
             ('unit_decl',
              'F',
              'ℝ',
              [('m', 1), ('kg', 1), ('s', -2)],
              ('mul', ('var', 'm'), ('var', 'a')),
              14),
             ('expr', ('var', 'F'), 0),
             ('unit_decl',
              'F_bad_typed',
              'ℝ',
              [('m', 1), ('s', -2)],
              ('mul', ('var', 'm'), ('var', 'a')),
              18),
             ('expr', ('var', 'F_bad_typed'), 0),
             ('unit_decl', 'v', 'ℝ', [('m', 1), ('s', -1)], ('num', 3.0), 23),
             ('unit_decl', 'd', 'ℝ', [('m', 1)], ('num', 9.0), 24),
             ('assign', 't', ('div', ('var', 'd'), ('var', 'v')), 25),
             ('expr', ('var', 't'), 0),
             ('expr', ('var', 'd'), 0),
             ('expr', ('var', 'v'), 0),
             ('unit_decl', 'temp', 'ℝ', [('K', 1)], ('num', 100.0), 33),
             ('expr',
              ('mul',
               ('mul',
                ('mul', ('mul', ('var', 'F'), ('var', 'v')), ('var', 't')),
                ('var', 'F')),
               ('var', 'temp')),
              0),
             ('decl', 'F', 'ℝ', ('num', 3.0), 38),
             ('expr', ('var', 'F'), 0)]}
