EXPECTED = {'functions': {'neighbor_sum': {'params': [('eta',
                                            ('tensor',
                                             [('m', 'invariant'),
                                              ('n', 'invariant')]))],
                                'return_type': ('tensor',
                                                [('m', 'invariant'),
                                                 ('n', 'invariant')]),
                                'body': ('var', 's'),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                's',
                                                ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                                ('add',
                                                 ('add',
                                                  ('add',
                                                   ('call',
                                                    'roll',
                                                    [('var', 'eta'),
                                                     ('num', 1),
                                                     ('num', 0)]),
                                                   ('call',
                                                    'roll',
                                                    [('var', 'eta'),
                                                     ('neg', ('num', 1)),
                                                     ('num', 0)])),
                                                  ('call',
                                                   'roll',
                                                   [('var', 'eta'),
                                                    ('num', 1),
                                                    ('num', 1)])),
                                                 ('call',
                                                  'roll',
                                                  [('var', 'eta'),
                                                   ('neg', ('num', 1)),
                                                   ('num', 1)])))]},
               'semi_implicit_step': {'params': [('eta',
                                                  ('tensor',
                                                   [('m', 'invariant'),
                                                    ('n', 'invariant')])),
                                                 ('eps', 'ℝ')],
                                      'return_type': ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]),
                                      'body': ('var', 'next_eta'),
                                      'has_loop': False,
                                      'statements': [('body_decl',
                                                      'coeff',
                                                      'ℝ',
                                                      ('div',
                                                       ('mul',
                                                        ('var', 'dt'),
                                                        ('pow',
                                                         ('var', 'eps'),
                                                         ('num', 2))),
                                                       ('pow',
                                                        ('var', 'dx'),
                                                        ('num', 2)))),
                                                     ('body_decl',
                                                      'diag',
                                                      'ℝ',
                                                      ('add',
                                                       ('add',
                                                        ('num', 1.0),
                                                        ('mul',
                                                         ('var', 'dt'),
                                                         ('var', 'stab'))),
                                                       ('mul',
                                                        ('num', 4.0),
                                                        ('var', 'coeff')))),
                                                     ('body_decl',
                                                      'rhs',
                                                      ('tensor',
                                                       [('m', 'invariant'),
                                                        ('n', 'invariant')]),
                                                      ('sub',
                                                       ('mul',
                                                        ('add',
                                                         ('num', 1.0),
                                                         ('mul',
                                                          ('var', 'dt'),
                                                          ('var', 'stab'))),
                                                        ('var', 'eta')),
                                                       ('mul',
                                                        ('var', 'dt'),
                                                        ('sub',
                                                         ('pow',
                                                          ('var', 'eta'),
                                                          ('num', 3)),
                                                         ('var', 'eta'))))),
                                                     ('body_decl',
                                                      'next_eta',
                                                      ('tensor',
                                                       [('m', 'invariant'),
                                                        ('n', 'invariant')]),
                                                      ('var', 'eta')),
                                                     ('body_for_range',
                                                      'k',
                                                      ('num', 0),
                                                      ('var', 'jacobi_iters'),
                                                      [('loop_assign',
                                                        'next_eta',
                                                        ('div',
                                                         ('add',
                                                          ('var', 'rhs'),
                                                          ('mul',
                                                           ('var', 'coeff'),
                                                           ('call',
                                                            'neighbor_sum',
                                                            [('var',
                                                              'next_eta')]))),
                                                         ('var', 'diag')))])]},
               'solver': {'params': [('eps', 'ℝ')],
                          'return_type': ('tensor',
                                          [('m', 'invariant'),
                                           ('n', 'invariant')]),
                          'body': ('var', 'eta'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'eta',
                                          ('tensor',
                                           [('m', 'invariant'),
                                            ('n', 'invariant')]),
                                          ('var', 'ic')),
                                         ('body_for_range',
                                          's',
                                          ('num', 0),
                                          ('var', 'num_steps'),
                                          [('loop_assign',
                                            'eta',
                                            ('call',
                                             'semi_implicit_step',
                                             [('var', 'eta'),
                                              ('var', 'eps')]))])]},
               'calculate_loss': {'params': [('eps', 'ℝ')],
                                  'return_type': 'ℝ',
                                  'body': ('var', 'loss'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'pred',
                                                  ('tensor',
                                                   [('m', 'invariant'),
                                                    ('n', 'invariant')]),
                                                  ('call',
                                                   'solver',
                                                   [('var', 'eps')])),
                                                 ('body_decl',
                                                  'loss',
                                                  'ℝ',
                                                  ('call',
                                                   'mean',
                                                   [('pow',
                                                     ('sub',
                                                      ('var', 'pred'),
                                                      ('var', 'true_values')),
                                                     ('num', 2))]))]}},
 'classes': {},
 'program': [('func_def', 'neighbor_sum'),
             ('decl', 'Nx', 'ℕ', ('num', 64), 14),
             ('decl', 'dx', 'ℝ', ('div', ('num', 1.0), ('var', 'Nx')), 15),
             ('decl', 'dt', 'ℝ', ('num', 0.02), 16),
             ('decl', 'stab', 'ℝ', ('num', 2.0), 17),
             ('decl', 'jacobi_iters', 'ℕ', ('num', 12), 18),
             ('decl', 'num_steps', 'ℕ', ('num', 80), 19),
             ('decl',
              'ic',
              ('tensor', [('Nx', 'invariant'), ('Nx', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'Nx'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('Nx', 'invariant')]),
                ('call',
                 'Uniform',
                 [('neg', ('num', 0.1)), ('num', 0.1), ('var', 'Nx')]))),
              21),
             ('func_def', 'semi_implicit_step'),
             ('func_def', 'solver'),
             ('decl', 'true_eps', 'ℝ', ('num', 0.03), 41),
             ('decl',
              'true_values',
              ('tensor', [('m', 'invariant'), ('n', 'invariant')]),
              ('call', 'solver', [('var', 'true_eps')]),
              42),
             ('func_def', 'calculate_loss'),
             ('decl', 'eps', 'ℝ', ('num', 0.06), 57),
             ('decl', 'learning_rate', 'ℝ', ('num', 0.5), 58),
             ('decl', 'epochs', 'ℕ', ('num', 1), 64),
             ('for_loop_range',
              'epoch',
              ('num', 0),
              ('var', 'epochs'),
              [('for_assign',
                'g',
                ('call', 'grad', [('var', 'calculate_loss'), ('var', 'eps')])),
               ('for_assign',
                'eps',
                ('sub',
                 ('var', 'eps'),
                 ('mul', ('var', 'learning_rate'), ('var', 'g')))),
               ('for_call', 'print', [('var', 'eps')])],
              66)]}
