EXPECTED = {'functions': {'zero_array': {'params': [('length', 'ℕ')],
                              'return_type': ('tensor', [('length', 'invariant')]),
                              'body': ('var', 'values'),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'values',
                                              ('tensor', [('length', 'invariant')]),
                                              ('for_expr',
                                               'index',
                                               ('var', 'length'),
                                               ('mul',
                                                ('var', 'index'),
                                                ('num', 0.0))))]},
               'morse_model_potential': {'params': [('dissociation_eV', 'ℝ'),
                                                    ('α_inverse_angstrom', 'ℝ'),
                                                    ('equilibrium_angstrom', 'ℝ')],
                                         'return_type': ('tensor',
                                                         [('N_reference_points',
                                                           'invariant')]),
                                         'body': ('var', 'model_potential'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'model_potential',
                                                         ('tensor',
                                                          [('N_reference_points',
                                                            'invariant')]),
                                                         ('call',
                                                          'zero_array',
                                                          [('var',
                                                            'N_reference_points')])),
                                                        ('body_for_range',
                                                         'reference_index',
                                                         ('num', 0),
                                                         ('var', 'N_reference_points'),
                                                         [('loop_index_assign_nd',
                                                           'model_potential',
                                                           [('index_item',
                                                             ('var',
                                                              'reference_index'))],
                                                           ('mul',
                                                            ('var', 'dissociation_eV'),
                                                            ('pow',
                                                             ('sub',
                                                              ('num', 1.0),
                                                              ('call',
                                                               'exp',
                                                               [('mul',
                                                                 ('neg',
                                                                  ('var',
                                                                   'α_inverse_angstrom')),
                                                                 ('sub',
                                                                  ('index',
                                                                   'reference_bond_distance_angstrom',
                                                                   ('var',
                                                                    'reference_index')),
                                                                  ('var',
                                                                   'equilibrium_angstrom')))])),
                                                             ('num', 2))))])]},
               'morse_parameter_loss': {'params': [('dissociation_eV', 'ℝ'),
                                                   ('α_inverse_angstrom', 'ℝ'),
                                                   ('equilibrium_angstrom', 'ℝ')],
                                        'return_type': 'ℝ',
                                        'body': ('div',
                                                 ('var', 'total_loss'),
                                                 ('mul',
                                                  ('var', 'N_reference_points'),
                                                  ('num', 1.0))),
                                        'has_loop': False,
                                        'statements': [('body_decl',
                                                        'predicted',
                                                        ('tensor',
                                                         [('N_reference_points',
                                                           'invariant')]),
                                                        ('call',
                                                         'morse_model_potential',
                                                         [('var', 'dissociation_eV'),
                                                          ('var', 'α_inverse_angstrom'),
                                                          ('var',
                                                           'equilibrium_angstrom')])),
                                                       ('body_decl',
                                                        'total_loss',
                                                        'ℝ',
                                                        ('num', 0.0)),
                                                       ('body_decl',
                                                        'error',
                                                        'ℝ',
                                                        ('num', 0.0)),
                                                       ('body_for_range',
                                                        'reference_index',
                                                        ('num', 0),
                                                        ('var', 'N_reference_points'),
                                                        [('loop_assign',
                                                          'error',
                                                          ('sub',
                                                           ('index',
                                                            'predicted',
                                                            ('var', 'reference_index')),
                                                           ('index',
                                                            'reference_potential_eV',
                                                            ('var',
                                                             'reference_index')))),
                                                         ('loop_assign',
                                                          'total_loss',
                                                          ('add',
                                                           ('var', 'total_loss'),
                                                           ('pow',
                                                            ('var', 'error'),
                                                            ('num', 2))))])]},
               'loss_with_respect_to_dissociation': {'params': [('dissociation_eV',
                                                                 'ℝ')],
                                                     'return_type': 'ℝ',
                                                     'body': ('call',
                                                              'morse_parameter_loss',
                                                              [('var',
                                                                'dissociation_eV'),
                                                               ('var',
                                                                'learned_α_inverse_angstrom'),
                                                               ('var',
                                                                'learned_equilibrium_distance_angstrom')]),
                                                     'has_loop': False,
                                                     'statements': []},
               'loss_with_respect_to_α': {'params': [('α_inverse_angstrom', 'ℝ')],
                                          'return_type': 'ℝ',
                                          'body': ('call',
                                                   'morse_parameter_loss',
                                                   [('var',
                                                     'learned_dissociation_energy_eV'),
                                                    ('var', 'α_inverse_angstrom'),
                                                    ('var',
                                                     'learned_equilibrium_distance_angstrom')]),
                                          'has_loop': False,
                                          'statements': []},
               'loss_with_respect_to_equilibrium': {'params': [('equilibrium_angstrom',
                                                                'ℝ')],
                                                    'return_type': 'ℝ',
                                                    'body': ('call',
                                                             'morse_parameter_loss',
                                                             [('var',
                                                               'learned_dissociation_energy_eV'),
                                                              ('var',
                                                               'learned_α_inverse_angstrom'),
                                                              ('var',
                                                               'equilibrium_angstrom')]),
                                                    'has_loop': False,
                                                    'statements': []},
               'adam': {'params': [('parameter', 'ℝ'),
                                   ('gradient_value', 'ℝ'),
                                   ('first_moment', 'ℝ'),
                                   ('second_moment', 'ℝ'),
                                   ('step', 'ℝ'),
                                   ('learning_rate', 'ℝ')],
                        'return_type': ('tensor', [(4, 'invariant')]),
                        'body': ('array',
                                 [('var', 'new_parameter'),
                                  ('var', 'new_first_moment'),
                                  ('var', 'new_second_moment'),
                                  ('add', ('var', 'step'), ('num', 1.0))]),
                        'has_loop': False,
                        'statements': [('body_decl', 'β_1', 'ℝ', ('num', 0.9)),
                                       ('body_decl', 'β_2', 'ℝ', ('num', 0.999)),
                                       ('body_decl', 'ε', 'ℝ', ('num', 1e-08)),
                                       ('body_decl',
                                        'new_first_moment',
                                        'ℝ',
                                        ('add',
                                         ('mul',
                                          ('var', 'β_1'),
                                          ('var', 'first_moment')),
                                         ('mul',
                                          ('sub', ('num', 1.0), ('var', 'β_1')),
                                          ('var', 'gradient_value')))),
                                       ('body_decl',
                                        'new_second_moment',
                                        'ℝ',
                                        ('add',
                                         ('mul',
                                          ('var', 'β_2'),
                                          ('var', 'second_moment')),
                                         ('mul',
                                          ('sub', ('num', 1.0), ('var', 'β_2')),
                                          ('pow',
                                           ('var', 'gradient_value'),
                                           ('num', 2))))),
                                       ('body_decl',
                                        'corrected_first_moment',
                                        'ℝ',
                                        ('div',
                                         ('var', 'new_first_moment'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow', ('var', 'β_1'), ('var', 'step'))))),
                                       ('body_decl',
                                        'corrected_second_moment',
                                        'ℝ',
                                        ('div',
                                         ('var', 'new_second_moment'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow', ('var', 'β_2'), ('var', 'step'))))),
                                       ('body_decl',
                                        'new_parameter',
                                        'ℝ',
                                        ('sub',
                                         ('var', 'parameter'),
                                         ('div',
                                          ('mul',
                                           ('var', 'learning_rate'),
                                           ('var', 'corrected_first_moment')),
                                          ('add',
                                           ('call',
                                            'sqrt',
                                            [('var', 'corrected_second_moment')]),
                                           ('var', 'ε')))))]},
               'zero_matrix': {'params': [('rows', 'ℕ'), ('columns', 'ℕ')],
                               'return_type': ('tensor',
                                               [('rows', 'invariant'),
                                                ('columns', 'invariant')]),
                               'body': ('var', 'values'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'values',
                                               ('tensor',
                                                [('rows', 'invariant'),
                                                 ('columns', 'invariant')]),
                                               ('for_expr',
                                                'index',
                                                ('var', 'rows'),
                                                ('for_expr',
                                                 'column_index',
                                                 ('var', 'columns'),
                                                 ('mul',
                                                  ('add',
                                                   ('var', 'index'),
                                                   ('var', 'column_index')),
                                                  ('num', 0.0)))))]},
               'linspace': {'params': [('start', 'ℝ'), ('end', 'ℝ'), ('number', 'ℕ')],
                            'return_type': ('tensor', [('number', 'invariant')]),
                            'body': ('var', 'values'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'values',
                                            ('tensor', [('number', 'invariant')]),
                                            ('call',
                                             'zero_array',
                                             [('var', 'number')])),
                                           ('body_decl',
                                            'spacing',
                                            'ℝ',
                                            ('div',
                                             ('sub', ('var', 'end'), ('var', 'start')),
                                             ('sub', ('var', 'number'), ('num', 1)))),
                                           ('body_for_range',
                                            'index',
                                            ('num', 0),
                                            ('var', 'number'),
                                            [('loop_index_assign_nd',
                                              'values',
                                              [('index_item', ('var', 'index'))],
                                              ('add',
                                               ('var', 'start'),
                                               ('mul',
                                                ('var', 'index'),
                                                ('var', 'spacing'))))])]},
               'integrate': {'params': [('values', ('tensor', [('m', 'invariant')])),
                                        ('grid_spacing', 'ℝ'),
                                        ('number', 'ℕ')],
                             'return_type': 'ℝ',
                             'body': ('var', 'integral'),
                             'has_loop': False,
                             'statements': [('body_decl',
                                             'integral',
                                             'ℝ',
                                             ('num', 0.0)),
                                            ('body_for_range',
                                             'index',
                                             ('num', 0),
                                             ('var', 'number'),
                                             [('loop_assign',
                                               'integral',
                                               ('add',
                                                ('var', 'integral'),
                                                ('mul',
                                                 ('index', 'values', ('var', 'index')),
                                                 ('var', 'grid_spacing'))))])]},
               'dot_product': {'params': [('first', ('tensor', [('m', 'invariant')])),
                                          ('second', ('tensor', [('n', 'invariant')])),
                                          ('number', 'ℕ')],
                               'return_type': 'ℝ',
                               'body': ('var', 'value'),
                               'has_loop': False,
                               'statements': [('body_decl', 'value', 'ℝ', ('num', 0.0)),
                                              ('body_for_range',
                                               'index',
                                               ('num', 0),
                                               ('var', 'number'),
                                               [('loop_assign',
                                                 'value',
                                                 ('add',
                                                  ('var', 'value'),
                                                  ('mul',
                                                   ('index', 'first', ('var', 'index')),
                                                   ('index',
                                                    'second',
                                                    ('var', 'index')))))])]},
               'normalize_vector': {'params': [('values',
                                                ('tensor', [('m', 'invariant')])),
                                               ('number', 'ℕ')],
                                    'return_type': ('tensor',
                                                    [('number', 'invariant')]),
                                    'body': ('var', 'result'),
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'result',
                                                    ('tensor',
                                                     [('number', 'invariant')]),
                                                    ('call',
                                                     'zero_array',
                                                     [('var', 'number')])),
                                                   ('body_decl',
                                                    'norm',
                                                    'ℝ',
                                                    ('call',
                                                     'sqrt',
                                                     [('call',
                                                       'dot_product',
                                                       [('var', 'values'),
                                                        ('var', 'values'),
                                                        ('var', 'number')])])),
                                                   ('body_for_range',
                                                    'index',
                                                    ('num', 0),
                                                    ('var', 'number'),
                                                    [('loop_index_assign_nd',
                                                      'result',
                                                      [('index_item',
                                                        ('var', 'index'))],
                                                      ('div',
                                                       ('index',
                                                        'values',
                                                        ('var', 'index')),
                                                       ('var', 'norm')))])]},
               'apply_hamiltonian': {'params': [('wavefunction',
                                                 ('tensor', [('m', 'invariant')])),
                                                ('potential',
                                                 ('tensor', [('n', 'invariant')])),
                                                ('kinetic_coefficient', 'ℝ'),
                                                ('number', 'ℕ')],
                                     'return_type': ('tensor',
                                                     [('number', 'invariant')]),
                                     'body': ('var', 'result'),
                                     'has_loop': False,
                                     'statements': [('body_decl',
                                                     'result',
                                                     ('tensor',
                                                      [('number', 'invariant')]),
                                                     ('call',
                                                      'zero_array',
                                                      [('var', 'number')])),
                                                    ('body_index_assign',
                                                     'result',
                                                     ('num', 0),
                                                     ('sub',
                                                      ('mul',
                                                       ('add',
                                                        ('mul',
                                                         ('num', 2.0),
                                                         ('var',
                                                          'kinetic_coefficient')),
                                                        ('index',
                                                         'potential',
                                                         ('num', 0))),
                                                       ('index',
                                                        'wavefunction',
                                                        ('num', 0))),
                                                      ('mul',
                                                       ('var', 'kinetic_coefficient'),
                                                       ('index',
                                                        'wavefunction',
                                                        ('num', 1))))),
                                                    ('body_for_range',
                                                     'index',
                                                     ('num', 1),
                                                     ('sub',
                                                      ('var', 'number'),
                                                      ('num', 1)),
                                                     [('loop_index_assign_nd',
                                                       'result',
                                                       [('index_item',
                                                         ('var', 'index'))],
                                                       ('sub',
                                                        ('add',
                                                         ('mul',
                                                          ('neg',
                                                           ('var',
                                                            'kinetic_coefficient')),
                                                          ('index',
                                                           'wavefunction',
                                                           ('sub',
                                                            ('var', 'index'),
                                                            ('num', 1)))),
                                                         ('mul',
                                                          ('add',
                                                           ('mul',
                                                            ('num', 2.0),
                                                            ('var',
                                                             'kinetic_coefficient')),
                                                           ('index',
                                                            'potential',
                                                            ('var', 'index'))),
                                                          ('index',
                                                           'wavefunction',
                                                           ('var', 'index')))),
                                                        ('mul',
                                                         ('var', 'kinetic_coefficient'),
                                                         ('index',
                                                          'wavefunction',
                                                          ('add',
                                                           ('var', 'index'),
                                                           ('num', 1))))))]),
                                                    ('body_index_assign',
                                                     'result',
                                                     ('sub',
                                                      ('var', 'number'),
                                                      ('num', 1)),
                                                     ('add',
                                                      ('mul',
                                                       ('neg',
                                                        ('var', 'kinetic_coefficient')),
                                                       ('index',
                                                        'wavefunction',
                                                        ('sub',
                                                         ('var', 'number'),
                                                         ('num', 2)))),
                                                      ('mul',
                                                       ('add',
                                                        ('mul',
                                                         ('num', 2.0),
                                                         ('var',
                                                          'kinetic_coefficient')),
                                                        ('index',
                                                         'potential',
                                                         ('sub',
                                                          ('var', 'number'),
                                                          ('num', 1)))),
                                                       ('index',
                                                        'wavefunction',
                                                        ('sub',
                                                         ('var', 'number'),
                                                         ('num', 1))))))]},
               'jacobi_diagonalize': {'params': [],
                                      'return_type': 'ℕ',
                                      'body': ('var', 'jacobi_converged_local'),
                                      'has_loop': False,
                                      'statements': [('body_decl',
                                                      'jacobi_not_converged',
                                                      'ℕ',
                                                      ('num', 0)),
                                                     ('body_decl',
                                                      'jacobi_converged',
                                                      'ℕ',
                                                      ('num', 1)),
                                                     ('body_decl',
                                                      'jacobi_converged_local',
                                                      'ℕ',
                                                      ('var', 'jacobi_not_converged')),
                                                     ('body_for_range',
                                                      'index',
                                                      ('num', 0),
                                                      ('var', 'Krylov_dimension'),
                                                      [('loop_index_assign_nd',
                                                        'Ritz_vectors',
                                                        [('index_item',
                                                          ('var', 'index')),
                                                         ('index_item',
                                                          ('var', 'index'))],
                                                        ('num', 1.0)),
                                                       ('loop_for_range',
                                                        'column_index',
                                                        ('num', 0),
                                                        ('var', 'Krylov_dimension'),
                                                        [('loop_index_assign_nd',
                                                          'projected_work_matrix',
                                                          [('index_item',
                                                            ('var', 'index')),
                                                           ('index_item',
                                                            ('var', 'column_index'))],
                                                          ('indexN',
                                                           'projected_hamiltonian',
                                                           [('index_item',
                                                             ('var', 'index')),
                                                            ('index_item',
                                                             ('var',
                                                              'column_index'))]))])]),
                                                     ('body_for_range',
                                                      'rotation',
                                                      ('num', 0),
                                                      ('var',
                                                       'jacobi_maximum_rotations'),
                                                      [('loop_assign',
                                                        'jacobi_p',
                                                        ('num', 0)),
                                                       ('loop_assign',
                                                        'jacobi_q',
                                                        ('num', 1)),
                                                       ('loop_assign',
                                                        'jacobi_largest',
                                                        ('call',
                                                         'abs',
                                                         [('indexN',
                                                           'projected_work_matrix',
                                                           [('index_item', ('num', 0)),
                                                            ('index_item',
                                                             ('num', 1))])])),
                                                       ('loop_for_range',
                                                        'index',
                                                        ('num', 0),
                                                        ('var', 'Krylov_dimension'),
                                                        [('loop_for_range',
                                                          'column_index',
                                                          ('add',
                                                           ('var', 'index'),
                                                           ('num', 1)),
                                                          ('var', 'Krylov_dimension'),
                                                          [('loop_if',
                                                            ('cond_gt',
                                                             ('call',
                                                              'abs',
                                                              [('indexN',
                                                                'projected_work_matrix',
                                                                [('index_item',
                                                                  ('var', 'index')),
                                                                 ('index_item',
                                                                  ('var',
                                                                   'column_index'))])]),
                                                             ('var', 'jacobi_largest')),
                                                            [('loop_assign',
                                                              'jacobi_largest',
                                                              ('call',
                                                               'abs',
                                                               [('indexN',
                                                                 'projected_work_matrix',
                                                                 [('index_item',
                                                                   ('var', 'index')),
                                                                  ('index_item',
                                                                   ('var',
                                                                    'column_index'))])])),
                                                             ('loop_assign',
                                                              'jacobi_p',
                                                              ('var', 'index')),
                                                             ('loop_assign',
                                                              'jacobi_q',
                                                              ('var',
                                                               'column_index'))])])]),
                                                       ('loop_if',
                                                        ('cond_eq',
                                                         ('var',
                                                          'jacobi_converged_local'),
                                                         ('var',
                                                          'jacobi_not_converged')),
                                                        [('loop_if',
                                                          ('cond_leq',
                                                           ('var', 'jacobi_largest'),
                                                           ('var', 'jacobi_tolerance')),
                                                          [('loop_assign',
                                                            'jacobi_converged_local',
                                                            ('var',
                                                             'jacobi_converged'))])]),
                                                       ('loop_if',
                                                        ('cond_gt',
                                                         ('var', 'jacobi_largest'),
                                                         ('var', 'jacobi_tolerance')),
                                                        [('loop_assign',
                                                          'jacobi_angle',
                                                          ('mul',
                                                           ('num', 0.5),
                                                           ('call',
                                                            'atan2',
                                                            [('mul',
                                                              ('num', 2.0),
                                                              ('indexN',
                                                               'projected_work_matrix',
                                                               [('index_item',
                                                                 ('var', 'jacobi_p')),
                                                                ('index_item',
                                                                 ('var',
                                                                  'jacobi_q'))])),
                                                             ('sub',
                                                              ('indexN',
                                                               'projected_work_matrix',
                                                               [('index_item',
                                                                 ('var', 'jacobi_q')),
                                                                ('index_item',
                                                                 ('var', 'jacobi_q'))]),
                                                              ('indexN',
                                                               'projected_work_matrix',
                                                               [('index_item',
                                                                 ('var', 'jacobi_p')),
                                                                ('index_item',
                                                                 ('var',
                                                                  'jacobi_p'))]))]))),
                                                         ('loop_assign',
                                                          'jacobi_cosine',
                                                          ('call',
                                                           'cos',
                                                           [('var', 'jacobi_angle')])),
                                                         ('loop_assign',
                                                          'jacobi_sine',
                                                          ('call',
                                                           'sin',
                                                           [('var', 'jacobi_angle')])),
                                                         ('loop_assign',
                                                          'jacobi_app',
                                                          ('add',
                                                           ('indexN',
                                                            'projected_work_matrix',
                                                            [('index_item',
                                                              ('var', 'jacobi_p')),
                                                             ('index_item',
                                                              ('var', 'jacobi_p'))]),
                                                           ('num', 0.0))),
                                                         ('loop_assign',
                                                          'jacobi_aqq',
                                                          ('add',
                                                           ('indexN',
                                                            'projected_work_matrix',
                                                            [('index_item',
                                                              ('var', 'jacobi_q')),
                                                             ('index_item',
                                                              ('var', 'jacobi_q'))]),
                                                           ('num', 0.0))),
                                                         ('loop_assign',
                                                          'jacobi_apq',
                                                          ('add',
                                                           ('indexN',
                                                            'projected_work_matrix',
                                                            [('index_item',
                                                              ('var', 'jacobi_p')),
                                                             ('index_item',
                                                              ('var', 'jacobi_q'))]),
                                                           ('num', 0.0))),
                                                         ('loop_for_range',
                                                          'basis_index',
                                                          ('num', 0),
                                                          ('var', 'Krylov_dimension'),
                                                          [('loop_if',
                                                            ('cond_neq',
                                                             ('var', 'basis_index'),
                                                             ('var', 'jacobi_p')),
                                                            [('loop_if',
                                                              ('cond_neq',
                                                               ('var', 'basis_index'),
                                                               ('var', 'jacobi_q')),
                                                              [('loop_assign',
                                                                'jacobi_akp',
                                                                ('add',
                                                                 ('indexN',
                                                                  'projected_work_matrix',
                                                                  [('index_item',
                                                                    ('var',
                                                                     'basis_index')),
                                                                   ('index_item',
                                                                    ('var',
                                                                     'jacobi_p'))]),
                                                                 ('num', 0.0))),
                                                               ('loop_assign',
                                                                'jacobi_akq',
                                                                ('add',
                                                                 ('indexN',
                                                                  'projected_work_matrix',
                                                                  [('index_item',
                                                                    ('var',
                                                                     'basis_index')),
                                                                   ('index_item',
                                                                    ('var',
                                                                     'jacobi_q'))]),
                                                                 ('num', 0.0))),
                                                               ('loop_index_assign_nd',
                                                                'projected_work_matrix',
                                                                [('index_item',
                                                                  ('var',
                                                                   'basis_index')),
                                                                 ('index_item',
                                                                  ('var', 'jacobi_p'))],
                                                                ('sub',
                                                                 ('mul',
                                                                  ('var',
                                                                   'jacobi_cosine'),
                                                                  ('var',
                                                                   'jacobi_akp')),
                                                                 ('mul',
                                                                  ('var',
                                                                   'jacobi_sine'),
                                                                  ('var',
                                                                   'jacobi_akq')))),
                                                               ('loop_index_assign_nd',
                                                                'projected_work_matrix',
                                                                [('index_item',
                                                                  ('var', 'jacobi_p')),
                                                                 ('index_item',
                                                                  ('var',
                                                                   'basis_index'))],
                                                                ('indexN',
                                                                 'projected_work_matrix',
                                                                 [('index_item',
                                                                   ('var',
                                                                    'basis_index')),
                                                                  ('index_item',
                                                                   ('var',
                                                                    'jacobi_p'))])),
                                                               ('loop_index_assign_nd',
                                                                'projected_work_matrix',
                                                                [('index_item',
                                                                  ('var',
                                                                   'basis_index')),
                                                                 ('index_item',
                                                                  ('var', 'jacobi_q'))],
                                                                ('add',
                                                                 ('mul',
                                                                  ('var',
                                                                   'jacobi_sine'),
                                                                  ('var',
                                                                   'jacobi_akp')),
                                                                 ('mul',
                                                                  ('var',
                                                                   'jacobi_cosine'),
                                                                  ('var',
                                                                   'jacobi_akq')))),
                                                               ('loop_index_assign_nd',
                                                                'projected_work_matrix',
                                                                [('index_item',
                                                                  ('var', 'jacobi_q')),
                                                                 ('index_item',
                                                                  ('var',
                                                                   'basis_index'))],
                                                                ('indexN',
                                                                 'projected_work_matrix',
                                                                 [('index_item',
                                                                   ('var',
                                                                    'basis_index')),
                                                                  ('index_item',
                                                                   ('var',
                                                                    'jacobi_q'))]))])])]),
                                                         ('loop_index_assign_nd',
                                                          'projected_work_matrix',
                                                          [('index_item',
                                                            ('var', 'jacobi_p')),
                                                           ('index_item',
                                                            ('var', 'jacobi_p'))],
                                                          ('add',
                                                           ('sub',
                                                            ('mul',
                                                             ('mul',
                                                              ('var', 'jacobi_cosine'),
                                                              ('var', 'jacobi_cosine')),
                                                             ('var', 'jacobi_app')),
                                                            ('mul',
                                                             ('mul',
                                                              ('mul',
                                                               ('num', 2.0),
                                                               ('var', 'jacobi_sine')),
                                                              ('var', 'jacobi_cosine')),
                                                             ('var', 'jacobi_apq'))),
                                                           ('mul',
                                                            ('mul',
                                                             ('var', 'jacobi_sine'),
                                                             ('var', 'jacobi_sine')),
                                                            ('var', 'jacobi_aqq')))),
                                                         ('loop_index_assign_nd',
                                                          'projected_work_matrix',
                                                          [('index_item',
                                                            ('var', 'jacobi_q')),
                                                           ('index_item',
                                                            ('var', 'jacobi_q'))],
                                                          ('add',
                                                           ('add',
                                                            ('mul',
                                                             ('mul',
                                                              ('var', 'jacobi_sine'),
                                                              ('var', 'jacobi_sine')),
                                                             ('var', 'jacobi_app')),
                                                            ('mul',
                                                             ('mul',
                                                              ('mul',
                                                               ('num', 2.0),
                                                               ('var', 'jacobi_sine')),
                                                              ('var', 'jacobi_cosine')),
                                                             ('var', 'jacobi_apq'))),
                                                           ('mul',
                                                            ('mul',
                                                             ('var', 'jacobi_cosine'),
                                                             ('var', 'jacobi_cosine')),
                                                            ('var', 'jacobi_aqq')))),
                                                         ('loop_index_assign_nd',
                                                          'projected_work_matrix',
                                                          [('index_item',
                                                            ('var', 'jacobi_p')),
                                                           ('index_item',
                                                            ('var', 'jacobi_q'))],
                                                          ('num', 0.0)),
                                                         ('loop_index_assign_nd',
                                                          'projected_work_matrix',
                                                          [('index_item',
                                                            ('var', 'jacobi_q')),
                                                           ('index_item',
                                                            ('var', 'jacobi_p'))],
                                                          ('num', 0.0)),
                                                         ('loop_for_range',
                                                          'basis_index',
                                                          ('num', 0),
                                                          ('var', 'Krylov_dimension'),
                                                          [('loop_assign',
                                                            'jacobi_vkp',
                                                            ('add',
                                                             ('indexN',
                                                              'Ritz_vectors',
                                                              [('index_item',
                                                                ('var', 'basis_index')),
                                                               ('index_item',
                                                                ('var', 'jacobi_p'))]),
                                                             ('num', 0.0))),
                                                           ('loop_assign',
                                                            'jacobi_vkq',
                                                            ('add',
                                                             ('indexN',
                                                              'Ritz_vectors',
                                                              [('index_item',
                                                                ('var', 'basis_index')),
                                                               ('index_item',
                                                                ('var', 'jacobi_q'))]),
                                                             ('num', 0.0))),
                                                           ('loop_index_assign_nd',
                                                            'Ritz_vectors',
                                                            [('index_item',
                                                              ('var', 'basis_index')),
                                                             ('index_item',
                                                              ('var', 'jacobi_p'))],
                                                            ('sub',
                                                             ('mul',
                                                              ('var', 'jacobi_cosine'),
                                                              ('var', 'jacobi_vkp')),
                                                             ('mul',
                                                              ('var', 'jacobi_sine'),
                                                              ('var', 'jacobi_vkq')))),
                                                           ('loop_index_assign_nd',
                                                            'Ritz_vectors',
                                                            [('index_item',
                                                              ('var', 'basis_index')),
                                                             ('index_item',
                                                              ('var', 'jacobi_q'))],
                                                            ('add',
                                                             ('mul',
                                                              ('var', 'jacobi_sine'),
                                                              ('var', 'jacobi_vkp')),
                                                             ('mul',
                                                              ('var', 'jacobi_cosine'),
                                                              ('var',
                                                               'jacobi_vkq'))))])])]),
                                                     ('body_for_range',
                                                      'index',
                                                      ('num', 0),
                                                      ('var', 'Krylov_dimension'),
                                                      [('loop_index_assign_nd',
                                                        'Ritz_values',
                                                        [('index_item',
                                                          ('var', 'index'))],
                                                        ('indexN',
                                                         'projected_work_matrix',
                                                         [('index_item',
                                                           ('var', 'index')),
                                                          ('index_item',
                                                           ('var', 'index'))]))]),
                                                     ('body_for_range',
                                                      'index',
                                                      ('num', 0),
                                                      ('sub',
                                                       ('var', 'Krylov_dimension'),
                                                       ('num', 1)),
                                                      [('loop_assign',
                                                        'jacobi_minimum',
                                                        ('var', 'index')),
                                                       ('loop_for_range',
                                                        'column_index',
                                                        ('add',
                                                         ('var', 'index'),
                                                         ('num', 1)),
                                                        ('var', 'Krylov_dimension'),
                                                        [('loop_if',
                                                          ('cond_lt',
                                                           ('index',
                                                            'Ritz_values',
                                                            ('var', 'column_index')),
                                                           ('index',
                                                            'Ritz_values',
                                                            ('var', 'jacobi_minimum'))),
                                                          [('loop_assign',
                                                            'jacobi_minimum',
                                                            ('var',
                                                             'column_index'))])]),
                                                       ('loop_if',
                                                        ('cond_neq',
                                                         ('var', 'jacobi_minimum'),
                                                         ('var', 'index')),
                                                        [('loop_assign',
                                                          'jacobi_temporary_value',
                                                          ('add',
                                                           ('index',
                                                            'Ritz_values',
                                                            ('var', 'index')),
                                                           ('num', 0.0))),
                                                         ('loop_index_assign_nd',
                                                          'Ritz_values',
                                                          [('index_item',
                                                            ('var', 'index'))],
                                                          ('index',
                                                           'Ritz_values',
                                                           ('var', 'jacobi_minimum'))),
                                                         ('loop_index_assign_nd',
                                                          'Ritz_values',
                                                          [('index_item',
                                                            ('var', 'jacobi_minimum'))],
                                                          ('var',
                                                           'jacobi_temporary_value')),
                                                         ('loop_for_range',
                                                          'basis_index',
                                                          ('num', 0),
                                                          ('var', 'Krylov_dimension'),
                                                          [('loop_assign',
                                                            'jacobi_temporary_vector',
                                                            ('add',
                                                             ('indexN',
                                                              'Ritz_vectors',
                                                              [('index_item',
                                                                ('var', 'basis_index')),
                                                               ('index_item',
                                                                ('var', 'index'))]),
                                                             ('num', 0.0))),
                                                           ('loop_index_assign_nd',
                                                            'Ritz_vectors',
                                                            [('index_item',
                                                              ('var', 'basis_index')),
                                                             ('index_item',
                                                              ('var', 'index'))],
                                                            ('indexN',
                                                             'Ritz_vectors',
                                                             [('index_item',
                                                               ('var', 'basis_index')),
                                                              ('index_item',
                                                               ('var',
                                                                'jacobi_minimum'))])),
                                                           ('loop_index_assign_nd',
                                                            'Ritz_vectors',
                                                            [('index_item',
                                                              ('var', 'basis_index')),
                                                             ('index_item',
                                                              ('var',
                                                               'jacobi_minimum'))],
                                                            ('var',
                                                             'jacobi_temporary_vector'))])])])]}},
 'classes': {},
 'program': [('func_def', 'zero_array'),
             ('func_def', 'morse_model_potential'),
             ('func_def', 'morse_parameter_loss'),
             ('func_def', 'loss_with_respect_to_dissociation'),
             ('func_def', 'loss_with_respect_to_α'),
             ('func_def', 'loss_with_respect_to_equilibrium'),
             ('func_def', 'adam'),
             ('decl', 'atomic_mass_unit', 'ℝ', ('num', 1.6605390666e-27), 42),
             ('decl', 'ℏ', 'ℝ', ('num', 1.054571817e-34), 43),
             ('decl', 'planck_constant', 'ℝ', ('num', 6.62607015e-34), 44),
             ('decl', 'speed_of_light_cm', 'ℝ', ('num', 29979245800.0), 45),
             ('decl', 'electron_volt', 'ℝ', ('num', 1.602176634e-19), 46),
             ('decl',
              'inverse_angstrom_to_inverse_meter',
              'ℝ',
              ('num', 10000000000.0),
              47),
             ('decl', 'mass_H_u', 'ℝ', ('num', 1.00784), 48),
             ('decl', 'mass_Cl_u', 'ℝ', ('num', 35.45), 49),
             ('decl',
              'mass_H',
              'ℝ',
              ('mul', ('var', 'mass_H_u'), ('var', 'atomic_mass_unit')),
              50),
             ('decl',
              'mass_Cl',
              'ℝ',
              ('mul', ('var', 'mass_Cl_u'), ('var', 'atomic_mass_unit')),
              51),
             ('decl',
              'μ_HCl',
              'ℝ',
              ('div',
               ('mul', ('var', 'mass_H'), ('var', 'mass_Cl')),
               ('add', ('var', 'mass_H'), ('var', 'mass_Cl'))),
              52),
             ('decl', 'N_reference_points', 'ℕ', ('num', 13), 55),
             ('decl',
              'reference_bond_distance_angstrom',
              ('tensor', [('N_reference_points', 'invariant')]),
              ('array',
               [('num', 1.1),
                ('num', 1.2746),
                ('num', 1.6),
                ('num', 2.15),
                ('num', 2.65),
                ('num', 3.2),
                ('num', 3.75),
                ('num', 3.95),
                ('num', 4.25),
                ('num', 4.55),
                ('num', 4.8),
                ('num', 5.0),
                ('num', 5.3)]),
              57),
             ('decl',
              'reference_potential_eV',
              ('tensor', [('N_reference_points', 'invariant')]),
              ('array',
               [('num', 0.68888),
                ('num', 0.0),
                ('num', 0.97847),
                ('num', 3.22469),
                ('num', 4.2397),
                ('num', 4.54743),
                ('num', 4.60134),
                ('num', 4.60678),
                ('num', 4.61086),
                ('num', 4.61274),
                ('num', 4.61355),
                ('num', 4.61396),
                ('num', 4.61434)]),
              58),
             ('decl', 'learned_dissociation_energy_eV', 'ℝ', ('num', 3.5), 61),
             ('decl', 'learned_α_inverse_angstrom', 'ℝ', ('num', 1.5), 62),
             ('decl', 'learned_equilibrium_distance_angstrom', 'ℝ', ('num', 1.35), 63),
             ('decl', 'dissociation_first_moment', 'ℝ', ('num', 0.0), 64),
             ('decl', 'dissociation_second_moment', 'ℝ', ('num', 0.0), 65),
             ('decl', 'α_first_moment', 'ℝ', ('num', 0.0), 66),
             ('decl', 'α_second_moment', 'ℝ', ('num', 0.0), 67),
             ('decl', 'equilibrium_first_moment', 'ℝ', ('num', 0.0), 68),
             ('decl', 'equilibrium_second_moment', 'ℝ', ('num', 0.0), 69),
             ('decl', 'optimizer_step', 'ℝ', ('num', 1.0), 70),
             ('decl', 'learning_rate_dissociation', 'ℝ', ('num', 0.005), 73),
             ('decl', 'learning_rate_α', 'ℝ', ('num', 0.001), 74),
             ('decl', 'learning_rate_equilibrium', 'ℝ', ('num', 0.0005), 75),
             ('decl', 'learning_epochs', 'ℕ', ('num', 1), 81),
             ('decl', 'dissociation_gradient', 'ℝ', ('num', 0.0), 82),
             ('decl', 'α_gradient', 'ℝ', ('num', 0.0), 83),
             ('decl', 'equilibrium_gradient', 'ℝ', ('num', 0.0), 84),
             ('decl',
              'dissociation_adam_result',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('var', 'learned_dissociation_energy_eV'),
                ('num', 0.0),
                ('num', 0.0),
                ('var', 'optimizer_step')]),
              85),
             ('decl',
              'α_adam_result',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('var', 'learned_α_inverse_angstrom'),
                ('num', 0.0),
                ('num', 0.0),
                ('var', 'optimizer_step')]),
              86),
             ('decl',
              'equilibrium_adam_result',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('var', 'learned_equilibrium_distance_angstrom'),
                ('num', 0.0),
                ('num', 0.0),
                ('var', 'optimizer_step')]),
              87),
             ('decl',
              'loss_history',
              ('tensor', [('learning_epochs', 'invariant')]),
              ('call', 'zero_array', [('var', 'learning_epochs')]),
              88),
             ('for_loop_range',
              'epoch',
              ('num', 0),
              ('var', 'learning_epochs'),
              [('for_assign',
                'dissociation_gradient',
                ('call',
                 'grad',
                 [('var', 'loss_with_respect_to_dissociation'),
                  ('var', 'learned_dissociation_energy_eV')])),
               ('for_assign',
                'α_gradient',
                ('call',
                 'grad',
                 [('var', 'loss_with_respect_to_α'),
                  ('var', 'learned_α_inverse_angstrom')])),
               ('for_assign',
                'equilibrium_gradient',
                ('call',
                 'grad',
                 [('var', 'loss_with_respect_to_equilibrium'),
                  ('var', 'learned_equilibrium_distance_angstrom')])),
               ('for_assign',
                'dissociation_adam_result',
                ('call',
                 'adam',
                 [('var', 'learned_dissociation_energy_eV'),
                  ('var', 'dissociation_gradient'),
                  ('var', 'dissociation_first_moment'),
                  ('var', 'dissociation_second_moment'),
                  ('var', 'optimizer_step'),
                  ('var', 'learning_rate_dissociation')])),
               ('for_assign',
                'α_adam_result',
                ('call',
                 'adam',
                 [('var', 'learned_α_inverse_angstrom'),
                  ('var', 'α_gradient'),
                  ('var', 'α_first_moment'),
                  ('var', 'α_second_moment'),
                  ('var', 'optimizer_step'),
                  ('var', 'learning_rate_α')])),
               ('for_assign',
                'equilibrium_adam_result',
                ('call',
                 'adam',
                 [('var', 'learned_equilibrium_distance_angstrom'),
                  ('var', 'equilibrium_gradient'),
                  ('var', 'equilibrium_first_moment'),
                  ('var', 'equilibrium_second_moment'),
                  ('var', 'optimizer_step'),
                  ('var', 'learning_rate_equilibrium')])),
               ('for_assign',
                'learned_dissociation_energy_eV',
                ('index', 'dissociation_adam_result', ('num', 0))),
               ('for_assign',
                'dissociation_first_moment',
                ('index', 'dissociation_adam_result', ('num', 1))),
               ('for_assign',
                'dissociation_second_moment',
                ('index', 'dissociation_adam_result', ('num', 2))),
               ('for_assign',
                'learned_α_inverse_angstrom',
                ('index', 'α_adam_result', ('num', 0))),
               ('for_assign', 'α_first_moment', ('index', 'α_adam_result', ('num', 1))),
               ('for_assign',
                'α_second_moment',
                ('index', 'α_adam_result', ('num', 2))),
               ('for_assign',
                'learned_equilibrium_distance_angstrom',
                ('index', 'equilibrium_adam_result', ('num', 0))),
               ('for_assign',
                'equilibrium_first_moment',
                ('index', 'equilibrium_adam_result', ('num', 1))),
               ('for_assign',
                'equilibrium_second_moment',
                ('index', 'equilibrium_adam_result', ('num', 2))),
               ('for_index_assign_nd',
                'loss_history',
                [('index_item', ('var', 'epoch'))],
                ('call',
                 'morse_parameter_loss',
                 [('var', 'learned_dissociation_energy_eV'),
                  ('var', 'learned_α_inverse_angstrom'),
                  ('var', 'learned_equilibrium_distance_angstrom')])),
               ('for_assign',
                'optimizer_step',
                ('add', ('var', 'optimizer_step'), ('num', 1.0)))],
              91),
             ('decl',
              'final_learning_loss',
              'ℝ',
              ('call',
               'morse_parameter_loss',
               [('var', 'learned_dissociation_energy_eV'),
                ('var', 'learned_α_inverse_angstrom'),
                ('var', 'learned_equilibrium_distance_angstrom')]),
              111),
             ('decl',
              'learned_reference_potential_eV',
              ('tensor', [('N_reference_points', 'invariant')]),
              ('call',
               'morse_model_potential',
               [('var', 'learned_dissociation_energy_eV'),
                ('var', 'learned_α_inverse_angstrom'),
                ('var', 'learned_equilibrium_distance_angstrom')]),
              112),
             ('func_def', 'zero_matrix'),
             ('func_def', 'linspace'),
             ('func_def', 'integrate'),
             ('func_def', 'dot_product'),
             ('func_def', 'normalize_vector'),
             ('func_def', 'apply_hamiltonian'),
             ('func_def', 'jacobi_diagonalize'),
             ('decl',
              'dissociation_energy_eV',
              'ℝ',
              ('var', 'learned_dissociation_energy_eV'),
              219),
             ('decl',
              'dissociation_energy_J',
              'ℝ',
              ('mul', ('var', 'dissociation_energy_eV'), ('var', 'electron_volt')),
              220),
             ('decl',
              'equilibrium_distance',
              'ℝ',
              ('mul', ('var', 'learned_equilibrium_distance_angstrom'), ('num', 1e-10)),
              221),
             ('decl',
              'morse_α',
              'ℝ',
              ('mul',
               ('var', 'learned_α_inverse_angstrom'),
               ('var', 'inverse_angstrom_to_inverse_meter')),
              222),
             ('decl', 'N_grid', 'ℕ', ('num', 100), 225),
             ('decl', 'N_levels', 'ℕ', ('num', 2), 226),
             ('decl', 'block_size', 'ℕ', ('num', 2), 227),
             ('decl', 'Krylov_dimension', 'ℕ', ('num', 40), 228),
             ('decl', 'r_min', 'ℝ', ('num', 5e-11), 229),
             ('decl', 'r_max', 'ℝ', ('num', 2e-10), 230),
             ('decl',
              'grid_spacing',
              'ℝ',
              ('div',
               ('sub', ('var', 'r_max'), ('var', 'r_min')),
               ('add', ('var', 'N_grid'), ('num', 1))),
              231),
             ('decl',
              'r_start',
              'ℝ',
              ('add', ('var', 'r_min'), ('var', 'grid_spacing')),
              232),
             ('decl',
              'r_end',
              'ℝ',
              ('sub', ('var', 'r_max'), ('var', 'grid_spacing')),
              233),
             ('decl',
              'bond_distance',
              ('tensor', [('N_grid', 'invariant')]),
              ('call',
               'linspace',
               [('var', 'r_start'), ('var', 'r_end'), ('var', 'N_grid')]),
              234),
             ('decl',
              'distance_from_equilibrium',
              ('tensor', [('N_grid', 'invariant')]),
              ('sub', ('var', 'bond_distance'), ('var', 'equilibrium_distance')),
              237),
             ('decl',
              'morse_exponential',
              ('tensor', [('N_grid', 'invariant')]),
              ('call',
               'exp',
               [('mul',
                 ('neg', ('var', 'morse_α')),
                 ('var', 'distance_from_equilibrium'))]),
              238),
             ('decl',
              'morse_difference',
              ('tensor', [('N_grid', 'invariant')]),
              ('sub', ('num', 1.0), ('var', 'morse_exponential')),
              239),
             ('decl',
              'potential_J',
              ('tensor', [('N_grid', 'invariant')]),
              ('mul',
               ('mul', ('var', 'dissociation_energy_J'), ('var', 'morse_difference')),
               ('var', 'morse_difference')),
              240),
             ('decl',
              'potential_eV',
              ('tensor', [('N_grid', 'invariant')]),
              ('div', ('var', 'potential_J'), ('var', 'electron_volt')),
              241),
             ('decl',
              'kinetic_coefficient_J',
              'ℝ',
              ('mul',
               ('div', ('var', 'ℏ'), ('var', 'grid_spacing')),
               ('div',
                ('var', 'ℏ'),
                ('mul',
                 ('mul', ('num', 2.0), ('var', 'μ_HCl')),
                 ('var', 'grid_spacing')))),
              242),
             ('decl',
              'kinetic_coefficient_eV',
              'ℝ',
              ('div', ('var', 'kinetic_coefficient_J'), ('var', 'electron_volt')),
              243),
             ('decl', 'trial_width', 'ℝ', ('num', 2e-11), 246),
             ('decl',
              'gaussian_argument',
              ('tensor', [('N_grid', 'invariant')]),
              ('div', ('var', 'distance_from_equilibrium'), ('var', 'trial_width')),
              247),
             ('decl',
              'gaussian_envelope',
              ('tensor', [('N_grid', 'invariant')]),
              ('call',
               'exp',
               [('mul',
                 ('neg', ('var', 'gaussian_argument')),
                 ('var', 'gaussian_argument'))]),
              248),
             ('decl',
              'Krylov_basis',
              ('tensor', [('Krylov_dimension', 'invariant'), ('N_grid', 'invariant')]),
              ('call', 'zero_matrix', [('var', 'Krylov_dimension'), ('var', 'N_grid')]),
              251),
             ('decl',
              'H_Krylov',
              ('tensor', [('Krylov_dimension', 'invariant'), ('N_grid', 'invariant')]),
              ('call', 'zero_matrix', [('var', 'Krylov_dimension'), ('var', 'N_grid')]),
              252),
             ('decl',
              'projected_hamiltonian',
              ('tensor',
               [('Krylov_dimension', 'invariant'), ('Krylov_dimension', 'invariant')]),
              ('call',
               'zero_matrix',
               [('var', 'Krylov_dimension'), ('var', 'Krylov_dimension')]),
              253),
             ('decl',
              'projected_work_matrix',
              ('tensor',
               [('Krylov_dimension', 'invariant'), ('Krylov_dimension', 'invariant')]),
              ('call',
               'zero_matrix',
               [('var', 'Krylov_dimension'), ('var', 'Krylov_dimension')]),
              254),
             ('decl',
              'Ritz_vectors',
              ('tensor',
               [('Krylov_dimension', 'invariant'), ('Krylov_dimension', 'invariant')]),
              ('call',
               'zero_matrix',
               [('var', 'Krylov_dimension'), ('var', 'Krylov_dimension')]),
              255),
             ('decl',
              'Ritz_values',
              ('tensor', [('Krylov_dimension', 'invariant')]),
              ('call', 'zero_array', [('var', 'Krylov_dimension')]),
              256),
             ('decl', 'jacobi_tolerance', 'ℝ', ('num', 1e-07), 257),
             ('decl', 'jacobi_maximum_rotations', 'ℕ', ('num', 1), 261),
             ('decl', 'jacobi_p', 'ℕ', ('num', 0), 262),
             ('decl', 'jacobi_q', 'ℕ', ('num', 1), 263),
             ('decl',
              'candidate',
              ('tensor', [('N_grid', 'invariant')]),
              ('call', 'zero_array', [('var', 'N_grid')]),
              264),
             ('decl', 'overlap', 'ℝ', ('num', 0.0), 265),
             ('decl', 'candidate_norm', 'ℝ', ('num', 0.0), 266),
             ('for_loop_range',
              'index',
              ('num', 0),
              ('var', 'N_grid'),
              [('for_index_assign_nd',
                'Krylov_basis',
                [('index_item', ('num', 0)), ('index_item', ('var', 'index'))],
                ('index', 'gaussian_envelope', ('var', 'index')))],
              269),
             ('index_assign',
              'Krylov_basis',
              0,
              ('call',
               'normalize_vector',
               [('index', 'Krylov_basis', ('num', 0)), ('var', 'N_grid')]),
              271),
             ('for_loop_range',
              'q_index',
              ('num', 1),
              ('var', 'Krylov_dimension'),
              [('for_if_else',
                ('cond_lt', ('var', 'q_index'), ('var', 'block_size')),
                [('for_loop_range',
                  'index',
                  ('num', 0),
                  ('var', 'N_grid'),
                  [('for_index_assign_nd',
                    'candidate',
                    [('index_item', ('var', 'index'))],
                    ('mul',
                     ('index', 'gaussian_argument', ('var', 'index')),
                     ('indexN',
                      'Krylov_basis',
                      [('index_item', ('sub', ('var', 'q_index'), ('num', 1))),
                       ('index_item', ('var', 'index'))])))],
                  276)],
                [('for_assign',
                  'candidate',
                  ('call',
                   'apply_hamiltonian',
                   [('index',
                     'Krylov_basis',
                     ('sub', ('var', 'q_index'), ('var', 'block_size'))),
                    ('var', 'potential_eV'),
                    ('var', 'kinetic_coefficient_eV'),
                    ('var', 'N_grid')]))]),
               ('for_loop_range',
                'orthogonalization_pass',
                ('num', 0),
                ('num', 2),
                [('for_loop_range',
                  'lower',
                  ('num', 0),
                  ('var', 'q_index'),
                  [('for_assign',
                    'overlap',
                    ('call',
                     'dot_product',
                     [('index', 'Krylov_basis', ('var', 'lower')),
                      ('var', 'candidate'),
                      ('var', 'N_grid')])),
                   ('for_loop_range',
                    'index',
                    ('num', 0),
                    ('var', 'N_grid'),
                    [('for_index_assign_nd',
                      'candidate',
                      [('index_item', ('var', 'index'))],
                      ('sub',
                       ('index', 'candidate', ('var', 'index')),
                       ('mul',
                        ('var', 'overlap'),
                        ('indexN',
                         'Krylov_basis',
                         [('index_item', ('var', 'lower')),
                          ('index_item', ('var', 'index'))]))))],
                    283)],
                  281)],
                280),
               ('for_assign',
                'candidate_norm',
                ('call',
                 'sqrt',
                 [('call',
                   'dot_product',
                   [('var', 'candidate'), ('var', 'candidate'), ('var', 'N_grid')])])),
               ('for_loop_range',
                'index',
                ('num', 0),
                ('var', 'N_grid'),
                [('for_index_assign_nd',
                  'Krylov_basis',
                  [('index_item', ('var', 'q_index')),
                   ('index_item', ('var', 'index'))],
                  ('div',
                   ('index', 'candidate', ('var', 'index')),
                   ('var', 'candidate_norm')))],
                286)],
              274),
             ('for_loop_range',
              'q_index',
              ('num', 0),
              ('var', 'Krylov_dimension'),
              [('for_index_assign_nd',
                'H_Krylov',
                [('index_item', ('var', 'q_index'))],
                ('call',
                 'apply_hamiltonian',
                 [('index', 'Krylov_basis', ('var', 'q_index')),
                  ('var', 'potential_eV'),
                  ('var', 'kinetic_coefficient_eV'),
                  ('var', 'N_grid')]))],
              290),
             ('for_loop_range',
              'row',
              ('num', 0),
              ('var', 'Krylov_dimension'),
              [('for_loop_range',
                'column',
                ('var', 'row'),
                ('var', 'Krylov_dimension'),
                [('for_index_assign_nd',
                  'projected_hamiltonian',
                  [('index_item', ('var', 'row')), ('index_item', ('var', 'column'))],
                  ('call',
                   'dot_product',
                   [('index', 'Krylov_basis', ('var', 'row')),
                    ('index', 'H_Krylov', ('var', 'column')),
                    ('var', 'N_grid')])),
                 ('for_index_assign_nd',
                  'projected_hamiltonian',
                  [('index_item', ('var', 'column')), ('index_item', ('var', 'row'))],
                  ('indexN',
                   'projected_hamiltonian',
                   [('index_item', ('var', 'row')),
                    ('index_item', ('var', 'column'))]))],
                295)],
              294),
             ('expr', ('call', 'jacobi_diagonalize', []), 0),
             ('decl',
              'vibrational_energies_eV',
              ('tensor', [('N_levels', 'invariant')]),
              ('call', 'zero_array', [('var', 'N_levels')]),
              301),
             ('decl',
              'ψ_raw',
              ('tensor', [('N_levels', 'invariant'), ('N_grid', 'invariant')]),
              ('call', 'zero_matrix', [('var', 'N_levels'), ('var', 'N_grid')]),
              302),
             ('for_loop_range',
              'n',
              ('num', 0),
              ('var', 'N_levels'),
              [('for_index_assign_nd',
                'vibrational_energies_eV',
                [('index_item', ('var', 'n'))],
                ('index', 'Ritz_values', ('var', 'n'))),
               ('for_loop_range',
                'index',
                ('num', 0),
                ('var', 'N_grid'),
                [('for_loop_range',
                  'q_index',
                  ('num', 0),
                  ('var', 'Krylov_dimension'),
                  [('for_index_assign_nd',
                    'ψ_raw',
                    [('index_item', ('var', 'n')), ('index_item', ('var', 'index'))],
                    ('add',
                     ('indexN',
                      'ψ_raw',
                      [('index_item', ('var', 'n')), ('index_item', ('var', 'index'))]),
                     ('mul',
                      ('indexN',
                       'Krylov_basis',
                       [('index_item', ('var', 'q_index')),
                        ('index_item', ('var', 'index'))]),
                      ('indexN',
                       'Ritz_vectors',
                       [('index_item', ('var', 'q_index')),
                        ('index_item', ('var', 'n'))]))))],
                  308)],
                307),
               ('for_index_assign_nd',
                'ψ_raw',
                [('index_item', ('var', 'n'))],
                ('call',
                 'normalize_vector',
                 [('index', 'ψ_raw', ('var', 'n')), ('var', 'N_grid')]))],
              305),
             ('decl',
              'normalization_factor',
              ('tensor', [('N_levels', 'invariant')]),
              ('call', 'zero_array', [('var', 'N_levels')]),
              312),
             ('decl',
              'ψ',
              ('tensor', [('N_levels', 'invariant'), ('N_grid', 'invariant')]),
              ('call', 'zero_matrix', [('var', 'N_levels'), ('var', 'N_grid')]),
              313),
             ('for_loop_range',
              'n',
              ('num', 0),
              ('var', 'N_levels'),
              [('for_index_assign_nd',
                'normalization_factor',
                [('index_item', ('var', 'n'))],
                ('call',
                 'sqrt',
                 [('call',
                   'integrate',
                   [('mul',
                     ('index', 'ψ_raw', ('var', 'n')),
                     ('index', 'ψ_raw', ('var', 'n'))),
                    ('var', 'grid_spacing'),
                    ('var', 'N_grid')])])),
               ('for_loop_range',
                'index',
                ('num', 0),
                ('var', 'N_grid'),
                [('for_index_assign_nd',
                  'ψ',
                  [('index_item', ('var', 'n')), ('index_item', ('var', 'index'))],
                  ('div',
                   ('indexN',
                    'ψ_raw',
                    [('index_item', ('var', 'n')), ('index_item', ('var', 'index'))]),
                   ('index', 'normalization_factor', ('var', 'n'))))],
                318)],
              316),
             ('decl',
              'transition_eV',
              'ℝ',
              ('sub',
               ('index', 'vibrational_energies_eV', ('num', 1)),
               ('index', 'vibrational_energies_eV', ('num', 0))),
              322),
             ('decl',
              'transition_J',
              'ℝ',
              ('mul', ('var', 'transition_eV'), ('var', 'electron_volt')),
              323),
             ('decl',
              'wavenumber',
              'ℝ',
              ('div',
               ('var', 'transition_J'),
               ('mul', ('var', 'planck_constant'), ('var', 'speed_of_light_cm'))),
              324),
             ('decl',
              'wavelength_micrometer',
              'ℝ',
              ('div', ('num', 10000.0), ('var', 'wavenumber')),
              325),
             ('expr',
              ('call', 'physika_print', [('var', 'learned_dissociation_energy_eV')]),
              0),
             ('expr',
              ('call', 'physika_print', [('var', 'learned_α_inverse_angstrom')]),
              0),
             ('expr',
              ('call',
               'physika_print',
               [('var', 'learned_equilibrium_distance_angstrom')]),
              0),
             ('expr', ('call', 'physika_print', [('var', 'final_learning_loss')]), 0),
             ('expr',
              ('call',
               'physika_print',
               [('index', 'vibrational_energies_eV', ('num', 0))]),
              0),
             ('expr',
              ('call',
               'physika_print',
               [('index', 'vibrational_energies_eV', ('num', 1))]),
              0),
             ('expr', ('call', 'physika_print', [('var', 'transition_eV')]), 0),
             ('expr', ('call', 'physika_print', [('var', 'wavenumber')]), 0),
             ('expr',
              ('call', 'physika_print', [('var', 'wavelength_micrometer')]),
              0)]}
