EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'append': {'params': [('x', ('tensor', [('m', 'invariant')])),
                                     ('var', 'ℝ')],
                          'return_type': ('tensor', [('n', 'invariant')]),
                          'body': ('var', 'results'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'new_length',
                                          'ℝ',
                                          ('add',
                                           ('call',
                                            'get_1d_array_length',
                                            [('var', 'x')]),
                                           ('num', 1))),
                                         ('body_decl',
                                          'results',
                                          ('tensor',
                                           [('new_length', 'invariant')]),
                                          ('call',
                                           'zero_1d_array',
                                           [('var', 'new_length')])),
                                         ('body_decl',
                                          'len_x',
                                          'ℕ',
                                          ('call',
                                           'get_1d_array_length',
                                           [('var', 'x')])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'new_length'),
                                          [('loop_if_else',
                                            ('cond_lt',
                                             ('imaginary',),
                                             ('var', 'len_x')),
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('index_item', ('imaginary',))],
                                              ('index', 'x', ('imaginary',)))],
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('index_item', ('imaginary',))],
                                              ('var', 'var'))])])]},
               'alpha_m': {'params': [('V', 'ℝ')],
                           'return_type': 'ℝ',
                           'body': None,
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'x',
                                           'ℝ',
                                           ('add',
                                            ('var', 'V'),
                                            ('num', 40.0))),
                                          ('body_if_else_return',
                                           ('cond_lt',
                                            ('call', 'abs', [('var', 'x')]),
                                            ('num', 0.0001)),
                                           ('num', 1.0),
                                           ('div',
                                            ('mul', ('num', 0.1), ('var', 'x')),
                                            ('sub',
                                             ('num', 1.0),
                                             ('call',
                                              'exp',
                                              [('sub',
                                                ('num', 0.0),
                                                ('div',
                                                 ('var', 'x'),
                                                 ('num', 10.0)))]))))]},
               'beta_m': {'params': [('V', 'ℝ')],
                          'return_type': 'ℝ',
                          'body': ('mul',
                                   ('num', 4.0),
                                   ('call',
                                    'exp',
                                    [('sub',
                                      ('num', 0.0),
                                      ('div',
                                       ('add', ('var', 'V'), ('num', 65.0)),
                                       ('num', 18.0)))])),
                          'has_loop': False,
                          'statements': []},
               'alpha_h': {'params': [('V', 'ℝ')],
                           'return_type': 'ℝ',
                           'body': ('mul',
                                    ('num', 0.07),
                                    ('call',
                                     'exp',
                                     [('sub',
                                       ('num', 0.0),
                                       ('div',
                                        ('add', ('var', 'V'), ('num', 65.0)),
                                        ('num', 20.0)))])),
                           'has_loop': False,
                           'statements': []},
               'beta_h': {'params': [('V', 'ℝ')],
                          'return_type': 'ℝ',
                          'body': ('div',
                                   ('num', 1.0),
                                   ('add',
                                    ('num', 1.0),
                                    ('call',
                                     'exp',
                                     [('sub',
                                       ('num', 0.0),
                                       ('div',
                                        ('add', ('var', 'V'), ('num', 35.0)),
                                        ('num', 10.0)))]))),
                          'has_loop': False,
                          'statements': []},
               'alpha_n': {'params': [('V', 'ℝ')],
                           'return_type': 'ℝ',
                           'body': None,
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'x',
                                           'ℝ',
                                           ('add',
                                            ('var', 'V'),
                                            ('num', 55.0))),
                                          ('body_if_else_return',
                                           ('cond_lt',
                                            ('call', 'abs', [('var', 'x')]),
                                            ('num', 0.0001)),
                                           ('num', 0.1),
                                           ('div',
                                            ('mul',
                                             ('num', 0.01),
                                             ('var', 'x')),
                                            ('sub',
                                             ('num', 1.0),
                                             ('call',
                                              'exp',
                                              [('sub',
                                                ('num', 0.0),
                                                ('div',
                                                 ('var', 'x'),
                                                 ('num', 10.0)))]))))]},
               'beta_n': {'params': [('V', 'ℝ')],
                          'return_type': 'ℝ',
                          'body': ('mul',
                                   ('num', 0.125),
                                   ('call',
                                    'exp',
                                    [('sub',
                                      ('num', 0.0),
                                      ('div',
                                       ('add', ('var', 'V'), ('num', 65.0)),
                                       ('num', 80.0)))])),
                          'has_loop': False,
                          'statements': []},
               'f': {'params': [('state', ('tensor', [(4, 'invariant')])),
                                ('θ', ('tensor', [(3, 'invariant')]))],
                     'return_type': ('tensor', [(4, 'invariant')]),
                     'body': ('array',
                              [('var', 'dV'),
                               ('var', 'dmg'),
                               ('var', 'dhg'),
                               ('var', 'dng')]),
                     'has_loop': False,
                     'statements': [('body_decl',
                                     'V',
                                     'ℝ',
                                     ('index', 'state', ('num', 0))),
                                    ('body_decl',
                                     'mg',
                                     'ℝ',
                                     ('index', 'state', ('num', 1))),
                                    ('body_decl',
                                     'hg',
                                     'ℝ',
                                     ('index', 'state', ('num', 2))),
                                    ('body_decl',
                                     'ng',
                                     'ℝ',
                                     ('index', 'state', ('num', 3))),
                                    ('body_decl',
                                     'gNa',
                                     'ℝ',
                                     ('index', 'θ', ('num', 0))),
                                    ('body_decl',
                                     'gK',
                                     'ℝ',
                                     ('index', 'θ', ('num', 1))),
                                    ('body_decl',
                                     'gL',
                                     'ℝ',
                                     ('index', 'θ', ('num', 2))),
                                    ('body_decl',
                                     'am',
                                     'ℝ',
                                     ('call', 'alpha_m', [('var', 'V')])),
                                    ('body_decl',
                                     'bm',
                                     'ℝ',
                                     ('call', 'beta_m', [('var', 'V')])),
                                    ('body_decl',
                                     'ah',
                                     'ℝ',
                                     ('call', 'alpha_h', [('var', 'V')])),
                                    ('body_decl',
                                     'bh',
                                     'ℝ',
                                     ('call', 'beta_h', [('var', 'V')])),
                                    ('body_decl',
                                     'an',
                                     'ℝ',
                                     ('call', 'alpha_n', [('var', 'V')])),
                                    ('body_decl',
                                     'bn',
                                     'ℝ',
                                     ('call', 'beta_n', [('var', 'V')])),
                                    ('body_decl',
                                     'iNa',
                                     'ℝ',
                                     ('mul',
                                      ('mul',
                                       ('mul',
                                        ('mul',
                                         ('mul', ('var', 'gNa'), ('var', 'mg')),
                                         ('var', 'mg')),
                                        ('var', 'mg')),
                                       ('var', 'hg')),
                                      ('sub', ('var', 'V'), ('var', 'ENa')))),
                                    ('body_decl',
                                     'iK',
                                     'ℝ',
                                     ('mul',
                                      ('mul',
                                       ('mul',
                                        ('mul',
                                         ('mul', ('var', 'gK'), ('var', 'ng')),
                                         ('var', 'ng')),
                                        ('var', 'ng')),
                                       ('var', 'ng')),
                                      ('sub', ('var', 'V'), ('var', 'EK')))),
                                    ('body_decl',
                                     'iL',
                                     'ℝ',
                                     ('mul',
                                      ('var', 'gL'),
                                      ('sub', ('var', 'V'), ('var', 'EL')))),
                                    ('body_decl',
                                     'dV',
                                     'ℝ',
                                     ('div',
                                      ('sub',
                                       ('sub',
                                        ('sub',
                                         ('var', 'Iapp'),
                                         ('var', 'iNa')),
                                        ('var', 'iK')),
                                       ('var', 'iL')),
                                      ('var', 'Cm'))),
                                    ('body_decl',
                                     'dmg',
                                     'ℝ',
                                     ('sub',
                                      ('mul',
                                       ('var', 'am'),
                                       ('sub', ('num', 1.0), ('var', 'mg'))),
                                      ('mul', ('var', 'bm'), ('var', 'mg')))),
                                    ('body_decl',
                                     'dhg',
                                     'ℝ',
                                     ('sub',
                                      ('mul',
                                       ('var', 'ah'),
                                       ('sub', ('num', 1.0), ('var', 'hg'))),
                                      ('mul', ('var', 'bh'), ('var', 'hg')))),
                                    ('body_decl',
                                     'dng',
                                     'ℝ',
                                     ('sub',
                                      ('mul',
                                       ('var', 'an'),
                                       ('sub', ('num', 1.0), ('var', 'ng'))),
                                      ('mul', ('var', 'bn'), ('var', 'ng'))))]},
               'rk4_step': {'params': [('state',
                                        ('tensor', [(4, 'invariant')])),
                                       ('θ', ('tensor', [(3, 'invariant')]))],
                            'return_type': ('tensor', [(4, 'invariant')]),
                            'body': ('add',
                                     ('var', 'state'),
                                     ('mul',
                                      ('div', ('var', 'dt'), ('num', 6.0)),
                                      ('add',
                                       ('add',
                                        ('add',
                                         ('var', 'k1'),
                                         ('mul', ('num', 2.0), ('var', 'k2'))),
                                        ('mul', ('num', 2.0), ('var', 'k3'))),
                                       ('var', 'k4')))),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'k1',
                                            ('tensor', [(4, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'state'), ('var', 'θ')])),
                                           ('body_decl',
                                            'k2_state',
                                            ('tensor', [(4, 'invariant')]),
                                            ('add',
                                             ('var', 'state'),
                                             ('mul',
                                              ('mul',
                                               ('num', 0.5),
                                               ('var', 'dt')),
                                              ('var', 'k1')))),
                                           ('body_decl',
                                            'k2',
                                            ('tensor', [(4, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'k2_state'),
                                              ('var', 'θ')])),
                                           ('body_decl',
                                            'k3_state',
                                            ('tensor', [(4, 'invariant')]),
                                            ('add',
                                             ('var', 'state'),
                                             ('mul',
                                              ('mul',
                                               ('num', 0.5),
                                               ('var', 'dt')),
                                              ('var', 'k2')))),
                                           ('body_decl',
                                            'k3',
                                            ('tensor', [(4, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'k3_state'),
                                              ('var', 'θ')])),
                                           ('body_decl',
                                            'k4_state',
                                            ('tensor', [(4, 'invariant')]),
                                            ('add',
                                             ('var', 'state'),
                                             ('mul',
                                              ('var', 'dt'),
                                              ('var', 'k3')))),
                                           ('body_decl',
                                            'k4',
                                            ('tensor', [(4, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'k4_state'),
                                              ('var', 'θ')]))]},
               'solver': {'params': [('θ', ('tensor', [(3, 'invariant')]))],
                          'return_type': ('tensor',
                                          [(4, 'invariant'),
                                           ('m', 'invariant')]),
                          'body': ('array',
                                   [('var', 'V_array'),
                                    ('var', 'mg_array'),
                                    ('var', 'hg_array'),
                                    ('var', 'ng_array')]),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'state',
                                          ('tensor', [(4, 'invariant')]),
                                          ('array',
                                           [('neg', ('num', 65.0)),
                                            ('num', 0.0529),
                                            ('num', 0.5961),
                                            ('num', 0.3177)])),
                                         ('body_decl',
                                          'V_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('neg', ('num', 65.0))])),
                                         ('body_decl',
                                          'mg_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('num', 0.0529)])),
                                         ('body_decl',
                                          'hg_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('num', 0.5961)])),
                                         ('body_decl',
                                          'ng_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('num', 0.3177)])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'timesteps'),
                                          [('loop_assign',
                                            'results',
                                            ('call',
                                             'rk4_step',
                                             [('var', 'state'), ('var', 'θ')])),
                                           ('loop_assign',
                                            'V',
                                            ('index', 'results', ('num', 0))),
                                           ('loop_assign',
                                            'mg',
                                            ('index', 'results', ('num', 1))),
                                           ('loop_assign',
                                            'hg',
                                            ('index', 'results', ('num', 2))),
                                           ('loop_assign',
                                            'ng',
                                            ('index', 'results', ('num', 3))),
                                           ('loop_assign',
                                            'V_array',
                                            ('call',
                                             'append',
                                             [('var', 'V_array'),
                                              ('var', 'V')])),
                                           ('loop_assign',
                                            'mg_array',
                                            ('call',
                                             'append',
                                             [('var', 'mg_array'),
                                              ('var', 'mg')])),
                                           ('loop_assign',
                                            'hg_array',
                                            ('call',
                                             'append',
                                             [('var', 'hg_array'),
                                              ('var', 'hg')])),
                                           ('loop_assign',
                                            'ng_array',
                                            ('call',
                                             'append',
                                             [('var', 'ng_array'),
                                              ('var', 'ng')])),
                                           ('loop_assign',
                                            'state',
                                            ('var', 'results'))])]},
               'adjoint_grad': {'params': [('θ',
                                            ('tensor', [(3, 'invariant')]))],
                                'return_type': ('tensor', [('n', 'invariant')]),
                                'body': ('var', 'L'),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'states',
                                                ('tensor',
                                                 [(4, 'invariant'),
                                                  ('m', 'invariant')]),
                                                ('call',
                                                 'solver',
                                                 [('var', 'θ')])),
                                               ('body_decl',
                                                'V_array',
                                                ('tensor',
                                                 [('m', 'invariant')]),
                                                ('index',
                                                 'states',
                                                 ('num', 0))),
                                               ('body_decl',
                                                'mg_array',
                                                ('tensor',
                                                 [('m', 'invariant')]),
                                                ('index',
                                                 'states',
                                                 ('num', 1))),
                                               ('body_decl',
                                                'hg_array',
                                                ('tensor',
                                                 [('m', 'invariant')]),
                                                ('index',
                                                 'states',
                                                 ('num', 2))),
                                               ('body_decl',
                                                'ng_array',
                                                ('tensor',
                                                 [('m', 'invariant')]),
                                                ('index',
                                                 'states',
                                                 ('num', 3))),
                                               ('body_decl',
                                                'm',
                                                'ℝ',
                                                ('call',
                                                 'get_1d_array_length',
                                                 [('var', 'V_array')])),
                                               ('body_decl',
                                                's',
                                                ('tensor', [(4, 'invariant')]),
                                                ('array',
                                                 [('div',
                                                   ('sub',
                                                    ('index',
                                                     'V_array',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1))),
                                                    ('index',
                                                     'true_V',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1)))),
                                                   ('var', 'm')),
                                                  ('num', 0.0),
                                                  ('num', 0.0),
                                                  ('num', 0.0)])),
                                               ('body_decl',
                                                'L',
                                                ('tensor', [(3, 'invariant')]),
                                                ('call',
                                                 'zero_1d_array',
                                                 [('num', 3)])),
                                               ('body_for_range',
                                                'i',
                                                ('num', 0),
                                                ('sub',
                                                 ('var', 'm'),
                                                 ('num', 1)),
                                                [('loop_assign',
                                                  'idx',
                                                  ('sub',
                                                   ('sub',
                                                    ('var', 'm'),
                                                    ('num', 2)),
                                                   ('imaginary',))),
                                                 ('loop_assign',
                                                  'V',
                                                  ('index',
                                                   'V_array',
                                                   ('var', 'idx'))),
                                                 ('loop_assign',
                                                  'mg',
                                                  ('index',
                                                   'mg_array',
                                                   ('var', 'idx'))),
                                                 ('loop_assign',
                                                  'hg',
                                                  ('index',
                                                   'hg_array',
                                                   ('var', 'idx'))),
                                                 ('loop_assign',
                                                  'ng',
                                                  ('index',
                                                   'ng_array',
                                                   ('var', 'idx'))),
                                                 ('loop_assign',
                                                  'state',
                                                  ('array',
                                                   [('var', 'V'),
                                                    ('var', 'mg'),
                                                    ('var', 'hg'),
                                                    ('var', 'ng')])),
                                                 ('loop_assign',
                                                  'J_state',
                                                  ('call',
                                                   'grad',
                                                   [('call',
                                                     'rk4_step',
                                                     [('var', 'state'),
                                                      ('var', 'θ')]),
                                                    ('var', 'state')])),
                                                 ('loop_assign',
                                                  'J_theta',
                                                  ('call',
                                                   'grad',
                                                   [('call',
                                                     'rk4_step',
                                                     [('var', 'state'),
                                                      ('var', 'θ')]),
                                                    ('var', 'θ')])),
                                                 ('loop_pluseq',
                                                  'L',
                                                  ('matmul',
                                                   ('var', 's'),
                                                   ('var', 'J_theta'))),
                                                 ('loop_assign',
                                                  'residual',
                                                  ('array',
                                                   [('div',
                                                     ('sub',
                                                      ('index',
                                                       'V_array',
                                                       ('var', 'idx')),
                                                      ('index',
                                                       'true_V',
                                                       ('var', 'idx'))),
                                                     ('var', 'm')),
                                                    ('num', 0.0),
                                                    ('num', 0.0),
                                                    ('num', 0.0)])),
                                                 ('loop_assign',
                                                  's',
                                                  ('add',
                                                   ('var', 'residual'),
                                                   ('matmul',
                                                    ('var', 's'),
                                                    ('var', 'J_state'))))])]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'append'),
             ('decl', 'Cm', 'ℝ', ('num', 1.0), 52),
             ('decl', 'ENa', 'ℝ', ('num', 50.0), 53),
             ('decl', 'EK', 'ℝ', ('neg', ('num', 77.0)), 54),
             ('decl', 'EL', 'ℝ', ('neg', ('num', 54.387)), 55),
             ('decl', 'Iapp', 'ℝ', ('num', 10.0), 56),
             ('func_def', 'alpha_m'),
             ('func_def', 'beta_m'),
             ('func_def', 'alpha_h'),
             ('func_def', 'beta_h'),
             ('func_def', 'alpha_n'),
             ('func_def', 'beta_n'),
             ('func_def', 'f'),
             ('func_def', 'rk4_step'),
             ('decl', 'dt', 'ℝ', ('num', 0.05), 120),
             ('decl', 'timesteps', 'ℝ', ('num', 400), 121),
             ('func_def', 'solver'),
             ('decl',
              'true_theta',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 120.0), ('num', 36.0), ('num', 0.3)]),
              142),
             ('decl',
              'true_results',
              ('tensor', [(4, 'invariant'), ('m', 'invariant')]),
              ('call', 'solver', [('var', 'true_theta')]),
              143),
             ('decl',
              'true_V',
              ('tensor', [('m', 'invariant')]),
              ('index', 'true_results', ('num', 0)),
              144),
             ('func_def', 'adjoint_grad'),
             ('decl',
              'θ',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 100.0), ('num', 30.0), ('num', 0.5)]),
              176),
             ('decl', 'learning_rate', 'ℝ', ('num', 0.2), 177),
             ('decl', 'beta1', 'ℝ', ('num', 0.9), 178),
             ('decl', 'beta2', 'ℝ', ('num', 0.999), 179),
             ('decl', 'eps_adam', 'ℝ', ('num', 1e-08), 180),
             ('decl',
              'm_adam',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 0.0), ('num', 0.0), ('num', 0.0)]),
              181),
             ('decl',
              'v_adam',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 0.0), ('num', 0.0), ('num', 0.0)]),
              182),
             ('decl', 't_adam', 'ℝ', ('num', 0.0), 183),
             ('decl', 'epochs', 'ℕ', ('num', 1), 189),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_assign', 'g', ('call', 'adjoint_grad', [('var', 'θ')])),
               ('for_assign',
                't_adam',
                ('add', ('var', 't_adam'), ('num', 1.0))),
               ('for_assign',
                'm_adam',
                ('add',
                 ('mul', ('var', 'beta1'), ('var', 'm_adam')),
                 ('mul',
                  ('sub', ('num', 1.0), ('var', 'beta1')),
                  ('var', 'g')))),
               ('for_assign',
                'v_adam',
                ('add',
                 ('mul', ('var', 'beta2'), ('var', 'v_adam')),
                 ('mul',
                  ('sub', ('num', 1.0), ('var', 'beta2')),
                  ('mul', ('var', 'g'), ('var', 'g'))))),
               ('for_assign',
                'mhat',
                ('div',
                 ('var', 'm_adam'),
                 ('sub',
                  ('num', 1.0),
                  ('pow', ('var', 'beta1'), ('var', 't_adam'))))),
               ('for_assign',
                'vhat',
                ('div',
                 ('var', 'v_adam'),
                 ('sub',
                  ('num', 1.0),
                  ('pow', ('var', 'beta2'), ('var', 't_adam'))))),
               ('for_assign',
                'θ',
                ('sub',
                 ('var', 'θ'),
                 ('div',
                  ('mul', ('var', 'learning_rate'), ('var', 'mhat')),
                  ('add',
                   ('call', 'sqrt', [('var', 'vhat')]),
                   ('var', 'eps_adam')))))],
              191),
             ('assign',
              'pred_results',
              ('call', 'solver', [('var', 'θ')]),
              200)]}