EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'linspace': {'params': [('start', 'ℝ'),
                                       ('end', 'ℝ'),
                                       ('n', 'ℕ')],
                            'return_type': ('tensor', [('n', 'invariant')]),
                            'body': ('var', 'x'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'x',
                                            ('tensor', [('n', 'invariant')]),
                                            ('call',
                                             'zero_1d_array',
                                             [('var', 'n')])),
                                           ('body_decl',
                                            'Δx',
                                            'ℝ',
                                            ('div',
                                             ('sub',
                                              ('var', 'end'),
                                              ('var', 'start')),
                                             ('sub',
                                              ('var', 'n'),
                                              ('num', 1)))),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('var', 'n'),
                                            [('loop_index_assign_nd',
                                              'x',
                                              [('index_item', ('imaginary',))],
                                              ('add',
                                               ('var', 'start'),
                                               ('mul',
                                                ('imaginary',),
                                                ('var', 'Δx'))))])]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'central_difference_x': {'params': [('f',
                                                    ('tensor',
                                                     [('m', 'invariant'),
                                                      ('n', 'invariant')]))],
                                        'return_type': ('tensor',
                                                        [('m', 'invariant'),
                                                         ('n', 'invariant')]),
                                        'body': ('var', 'diff'),
                                        'has_loop': False,
                                        'statements': [('body_decl',
                                                        'diff',
                                                        ('tensor',
                                                         [('n_points',
                                                           'invariant'),
                                                          ('n_points',
                                                           'invariant')]),
                                                        ('call',
                                                         'zero_2d_array',
                                                         [('var', 'n_points'),
                                                          ('var',
                                                           'n_points')])),
                                                       ('body_index_assign_nd',
                                                        'diff',
                                                        [('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'n_points'),
                                                           ('num', 1))),
                                                         ('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'n_points'),
                                                           ('num', 1)))],
                                                        ('div',
                                                         ('sub',
                                                          ('indexN',
                                                           'f',
                                                           [('slice_item',
                                                             ('num', 1),
                                                             ('sub',
                                                              ('var',
                                                               'n_points'),
                                                              ('num', 1))),
                                                            ('slice_item',
                                                             ('num', 2),
                                                             ('var',
                                                              'n_points'))]),
                                                          ('indexN',
                                                           'f',
                                                           [('slice_item',
                                                             ('num', 1),
                                                             ('sub',
                                                              ('var',
                                                               'n_points'),
                                                              ('num', 1))),
                                                            ('slice_item',
                                                             ('num', 0),
                                                             ('sub',
                                                              ('var',
                                                               'n_points'),
                                                              ('num', 2)))])),
                                                         ('mul',
                                                          ('num', 2),
                                                          ('var',
                                                           'element_length'))))]},
               'central_difference_y': {'params': [('f',
                                                    ('tensor',
                                                     [('m', 'invariant'),
                                                      ('n', 'invariant')]))],
                                        'return_type': ('tensor',
                                                        [('m', 'invariant'),
                                                         ('n', 'invariant')]),
                                        'body': ('var', 'diff'),
                                        'has_loop': False,
                                        'statements': [('body_decl',
                                                        'diff',
                                                        ('tensor',
                                                         [('n_points',
                                                           'invariant'),
                                                          ('n_points',
                                                           'invariant')]),
                                                        ('call',
                                                         'zero_2d_array',
                                                         [('var', 'n_points'),
                                                          ('var',
                                                           'n_points')])),
                                                       ('body_index_assign_nd',
                                                        'diff',
                                                        [('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'n_points'),
                                                           ('num', 1))),
                                                         ('slice_item',
                                                          ('num', 1),
                                                          ('sub',
                                                           ('var', 'n_points'),
                                                           ('num', 1)))],
                                                        ('div',
                                                         ('sub',
                                                          ('indexN',
                                                           'f',
                                                           [('slice_item',
                                                             ('num', 2),
                                                             ('var',
                                                              'n_points')),
                                                            ('slice_item',
                                                             ('num', 1),
                                                             ('sub',
                                                              ('var',
                                                               'n_points'),
                                                              ('num', 1)))]),
                                                          ('indexN',
                                                           'f',
                                                           [('slice_item',
                                                             ('num', 0),
                                                             ('sub',
                                                              ('var',
                                                               'n_points'),
                                                              ('num', 2))),
                                                            ('slice_item',
                                                             ('num', 1),
                                                             ('sub',
                                                              ('var',
                                                               'n_points'),
                                                              ('num', 1)))])),
                                                         ('mul',
                                                          ('num', 2),
                                                          ('var',
                                                           'element_length'))))]},
               'laplace': {'params': [('f',
                                       ('tensor',
                                        [('m', 'invariant'),
                                         ('n', 'invariant')]))],
                           'return_type': ('tensor',
                                           [('m', 'invariant'),
                                            ('n', 'invariant')]),
                           'body': ('var', 'diff'),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'diff',
                                           ('tensor',
                                            [('n_points', 'invariant'),
                                             ('n_points', 'invariant')]),
                                           ('call',
                                            'zero_2d_array',
                                            [('var', 'n_points'),
                                             ('var', 'n_points')])),
                                          ('body_index_assign_nd',
                                           'diff',
                                           [('slice_item',
                                             ('num', 1),
                                             ('sub',
                                              ('var', 'n_points'),
                                              ('num', 1))),
                                            ('slice_item',
                                             ('num', 1),
                                             ('sub',
                                              ('var', 'n_points'),
                                              ('num', 1)))],
                                           ('div',
                                            ('sub',
                                             ('add',
                                              ('add',
                                               ('add',
                                                ('indexN',
                                                 'f',
                                                 [('slice_item',
                                                   ('num', 1),
                                                   ('sub',
                                                    ('var', 'n_points'),
                                                    ('num', 1))),
                                                  ('slice_item',
                                                   ('num', 0),
                                                   ('sub',
                                                    ('var', 'n_points'),
                                                    ('num', 2)))]),
                                                ('indexN',
                                                 'f',
                                                 [('slice_item',
                                                   ('num', 0),
                                                   ('sub',
                                                    ('var', 'n_points'),
                                                    ('num', 2))),
                                                  ('slice_item',
                                                   ('num', 1),
                                                   ('sub',
                                                    ('var', 'n_points'),
                                                    ('num', 1)))])),
                                               ('indexN',
                                                'f',
                                                [('slice_item',
                                                  ('num', 1),
                                                  ('sub',
                                                   ('var', 'n_points'),
                                                   ('num', 1))),
                                                 ('slice_item',
                                                  ('num', 2),
                                                  ('var', 'n_points'))])),
                                              ('indexN',
                                               'f',
                                               [('slice_item',
                                                 ('num', 2),
                                                 ('var', 'n_points')),
                                                ('slice_item',
                                                 ('num', 1),
                                                 ('sub',
                                                  ('var', 'n_points'),
                                                  ('num', 1)))])),
                                             ('mul',
                                              ('num', 4),
                                              ('indexN',
                                               'f',
                                               [('slice_item',
                                                 ('num', 1),
                                                 ('sub',
                                                  ('var', 'n_points'),
                                                  ('num', 1))),
                                                ('slice_item',
                                                 ('num', 1),
                                                 ('sub',
                                                  ('var', 'n_points'),
                                                  ('num', 1)))]))),
                                            ('pow',
                                             ('var', 'element_length'),
                                             ('num', 2))))]},
               'apply_u_bc': {'params': [('u',
                                          ('tensor',
                                           [('n_points', 'invariant'),
                                            ('n_points', 'invariant')]))],
                              'return_type': ('tensor',
                                              [('n_points', 'invariant'),
                                               ('n_points', 'invariant')]),
                              'body': ('var', 'u'),
                              'has_loop': False,
                              'statements': [('body_index_assign_nd',
                                              'u',
                                              [('index_item', ('num', 0)),
                                               ('slice_item', None, None)],
                                              ('num', 0.0)),
                                             ('body_index_assign_nd',
                                              'u',
                                              [('index_item',
                                                ('neg', ('num', 1))),
                                               ('slice_item', None, None)],
                                              ('var',
                                               'horizontal_velocity_top')),
                                             ('body_index_assign_nd',
                                              'u',
                                              [('slice_item', None, None),
                                               ('index_item', ('num', 0))],
                                              ('num', 0.0)),
                                             ('body_index_assign_nd',
                                              'u',
                                              [('slice_item', None, None),
                                               ('index_item',
                                                ('neg', ('num', 1)))],
                                              ('num', 0.0))]},
               'apply_v_bc': {'params': [('v',
                                          ('tensor',
                                           [('n_points', 'invariant'),
                                            ('n_points', 'invariant')]))],
                              'return_type': ('tensor',
                                              [('n_points', 'invariant'),
                                               ('n_points', 'invariant')]),
                              'body': ('var', 'v'),
                              'has_loop': False,
                              'statements': [('body_index_assign_nd',
                                              'v',
                                              [('index_item', ('num', 0)),
                                               ('slice_item', None, None)],
                                              ('num', 0.0)),
                                             ('body_index_assign_nd',
                                              'v',
                                              [('index_item',
                                                ('neg', ('num', 1))),
                                               ('slice_item', None, None)],
                                              ('num', 0.0)),
                                             ('body_index_assign_nd',
                                              'v',
                                              [('slice_item', None, None),
                                               ('index_item', ('num', 0))],
                                              ('num', 0.0)),
                                             ('body_index_assign_nd',
                                              'v',
                                              [('slice_item', None, None),
                                               ('index_item',
                                                ('neg', ('num', 1)))],
                                              ('num', 0.0))]},
               'apply_p_bc': {'params': [('p',
                                          ('tensor',
                                           [('n_points', 'invariant'),
                                            ('n_points', 'invariant')]))],
                              'return_type': ('tensor',
                                              [('n_points', 'invariant'),
                                               ('n_points', 'invariant')]),
                              'body': ('var', 'p'),
                              'has_loop': False,
                              'statements': [('body_index_assign_nd',
                                              'p',
                                              [('slice_item', None, None),
                                               ('index_item',
                                                ('neg', ('num', 1)))],
                                              ('indexN',
                                               'p',
                                               [('slice_item', None, None),
                                                ('index_item',
                                                 ('neg', ('num', 2)))])),
                                             ('body_index_assign_nd',
                                              'p',
                                              [('index_item', ('num', 0)),
                                               ('slice_item', None, None)],
                                              ('indexN',
                                               'p',
                                               [('index_item', ('num', 1)),
                                                ('slice_item', None, None)])),
                                             ('body_index_assign_nd',
                                              'p',
                                              [('slice_item', None, None),
                                               ('index_item', ('num', 0))],
                                              ('indexN',
                                               'p',
                                               [('slice_item', None, None),
                                                ('index_item', ('num', 1))])),
                                             ('body_index_assign_nd',
                                              'p',
                                              [('index_item',
                                                ('neg', ('num', 1))),
                                               ('slice_item', None, None)],
                                              ('num', 0.0))]},
               'advect_diffuse': {'params': [('f',
                                              ('tensor',
                                               [('n_points', 'invariant'),
                                                ('n_points', 'invariant')])),
                                             ('u',
                                              ('tensor',
                                               [('n_points', 'invariant'),
                                                ('n_points', 'invariant')])),
                                             ('v',
                                              ('tensor',
                                               [('n_points', 'invariant'),
                                                ('n_points', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [('n_points', 'invariant'),
                                                   ('n_points', 'invariant')]),
                                  'body': ('add',
                                           ('neg',
                                            ('add',
                                             ('mul',
                                              ('var', 'u'),
                                              ('call',
                                               'central_difference_x',
                                               [('var', 'f')])),
                                             ('mul',
                                              ('var', 'v'),
                                              ('call',
                                               'central_difference_y',
                                               [('var', 'f')])))),
                                           ('mul',
                                            ('var', 'ν'),
                                            ('call',
                                             'laplace',
                                             [('var', 'f')]))),
                                  'has_loop': False,
                                  'statements': []},
               'solve_pressure': {'params': [('p_init',
                                              ('tensor',
                                               [('n_points', 'invariant'),
                                                ('n_points', 'invariant')])),
                                             ('rhs',
                                              ('tensor',
                                               [('n_points', 'invariant'),
                                                ('n_points', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [('n_points', 'invariant'),
                                                   ('n_points', 'invariant')]),
                                  'body': ('var', 'p_prev'),
                                  'has_loop': False,
                                  'statements': [('body_assign',
                                                  'p_prev',
                                                  ('var', 'p_init')),
                                                 ('body_for_range',
                                                  'k',
                                                  ('num', 0),
                                                  ('var',
                                                   'n_pressure_poisson_iterations'),
                                                  [('loop_assign',
                                                    'p_next',
                                                    ('call',
                                                     'zero_2d_array',
                                                     [('var', 'n_points'),
                                                      ('var', 'n_points')])),
                                                   ('loop_index_assign_nd',
                                                    'p_next',
                                                    [('slice_item',
                                                      ('num', 1),
                                                      ('neg', ('num', 1))),
                                                     ('slice_item',
                                                      ('num', 1),
                                                      ('neg', ('num', 1)))],
                                                    ('mul',
                                                     ('num', 0.25),
                                                     ('sub',
                                                      ('add',
                                                       ('add',
                                                        ('add',
                                                         ('indexN',
                                                          'p_prev',
                                                          [('slice_item',
                                                            ('num', 1),
                                                            ('neg',
                                                             ('num', 1))),
                                                           ('slice_item',
                                                            None,
                                                            ('neg',
                                                             ('num', 2)))]),
                                                         ('indexN',
                                                          'p_prev',
                                                          [('slice_item',
                                                            None,
                                                            ('neg',
                                                             ('num', 2))),
                                                           ('slice_item',
                                                            ('num', 1),
                                                            ('neg',
                                                             ('num', 1)))])),
                                                        ('indexN',
                                                         'p_prev',
                                                         [('slice_item',
                                                           ('num', 1),
                                                           ('neg', ('num', 1))),
                                                          ('slice_item',
                                                           ('num', 2),
                                                           None)])),
                                                       ('indexN',
                                                        'p_prev',
                                                        [('slice_item',
                                                          ('num', 2),
                                                          None),
                                                         ('slice_item',
                                                          ('num', 1),
                                                          ('neg',
                                                           ('num', 1)))])),
                                                      ('mul',
                                                       ('pow',
                                                        ('var',
                                                         'element_length'),
                                                        ('num', 2)),
                                                       ('indexN',
                                                        'rhs',
                                                        [('slice_item',
                                                          ('num', 1),
                                                          ('neg', ('num', 1))),
                                                         ('slice_item',
                                                          ('num', 1),
                                                          ('neg',
                                                           ('num', 1)))]))))),
                                                   ('loop_assign',
                                                    'p_prev',
                                                    ('call',
                                                     'apply_p_bc',
                                                     [('var', 'p_next')]))])]},
               'solver': {'params': [('ρ', 'ℝ')],
                          'return_type': ('tensor',
                                          [(3, 'invariant'),
                                           ('n_points', 'invariant'),
                                           ('n_points', 'invariant')]),
                          'body': ('array',
                                   [('var', 'u'), ('var', 'v'), ('var', 'p')]),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'u',
                                          ('tensor',
                                           [('n_points', 'invariant'),
                                            ('n_points', 'invariant')]),
                                          ('call',
                                           'zero_2d_array',
                                           [('var', 'n_points'),
                                            ('var', 'n_points')])),
                                         ('body_decl',
                                          'v',
                                          ('tensor',
                                           [('n_points', 'invariant'),
                                            ('n_points', 'invariant')]),
                                          ('call',
                                           'zero_2d_array',
                                           [('var', 'n_points'),
                                            ('var', 'n_points')])),
                                         ('body_decl',
                                          'p',
                                          ('tensor',
                                           [('n_points', 'invariant'),
                                            ('n_points', 'invariant')]),
                                          ('call',
                                           'zero_2d_array',
                                           [('var', 'n_points'),
                                            ('var', 'n_points')])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'n_iterations'),
                                          [('loop_assign',
                                            'u_tent',
                                            ('call',
                                             'apply_u_bc',
                                             [('add',
                                               ('var', 'u'),
                                               ('mul',
                                                ('var', 'time_step_length'),
                                                ('call',
                                                 'advect_diffuse',
                                                 [('var', 'u'),
                                                  ('var', 'u'),
                                                  ('var', 'v')])))])),
                                           ('loop_assign',
                                            'v_tent',
                                            ('call',
                                             'apply_v_bc',
                                             [('add',
                                               ('var', 'v'),
                                               ('mul',
                                                ('var', 'time_step_length'),
                                                ('call',
                                                 'advect_diffuse',
                                                 [('var', 'v'),
                                                  ('var', 'u'),
                                                  ('var', 'v')])))])),
                                           ('loop_assign',
                                            'rhs',
                                            ('mul',
                                             ('div',
                                              ('var', 'ρ'),
                                              ('var', 'time_step_length')),
                                             ('add',
                                              ('call',
                                               'central_difference_x',
                                               [('var', 'u_tent')]),
                                              ('call',
                                               'central_difference_y',
                                               [('var', 'v_tent')])))),
                                           ('loop_assign',
                                            'p',
                                            ('call',
                                             'solve_pressure',
                                             [('var', 'p'), ('var', 'rhs')])),
                                           ('loop_assign',
                                            'u',
                                            ('call',
                                             'apply_u_bc',
                                             [('sub',
                                               ('var', 'u_tent'),
                                               ('mul',
                                                ('div',
                                                 ('var', 'time_step_length'),
                                                 ('var', 'ρ')),
                                                ('call',
                                                 'central_difference_x',
                                                 [('var', 'p')])))])),
                                           ('loop_assign',
                                            'v',
                                            ('call',
                                             'apply_v_bc',
                                             [('sub',
                                               ('var', 'v_tent'),
                                               ('mul',
                                                ('div',
                                                 ('var', 'time_step_length'),
                                                 ('var', 'ρ')),
                                                ('call',
                                                 'central_difference_y',
                                                 [('var', 'p')])))]))])]},
               'calculate_loss': {'params': [('ρ', 'ℝ')],
                                  'return_type': 'ℝ',
                                  'body': ('var', 'loss'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'predictions',
                                                  ('tensor',
                                                   [(3, 'invariant'),
                                                    ('n_points', 'invariant'),
                                                    ('n_points', 'invariant')]),
                                                  ('call',
                                                   'solver',
                                                   [('var', 'ρ')])),
                                                 ('body_decl',
                                                  'pred_u',
                                                  ('tensor',
                                                   [('n_points', 'invariant'),
                                                    ('n_points', 'invariant')]),
                                                  ('index',
                                                   'predictions',
                                                   ('num', 0))),
                                                 ('body_decl',
                                                  'pred_v',
                                                  ('tensor',
                                                   [('n_points', 'invariant'),
                                                    ('n_points', 'invariant')]),
                                                  ('index',
                                                   'predictions',
                                                   ('num', 1))),
                                                 ('body_decl',
                                                  'pred_p',
                                                  ('tensor',
                                                   [('n_points', 'invariant'),
                                                    ('n_points', 'invariant')]),
                                                  ('index',
                                                   'predictions',
                                                   ('num', 2))),
                                                 ('body_decl',
                                                  'loss_u',
                                                  'ℝ',
                                                  ('call',
                                                   'mean',
                                                   [('pow',
                                                     ('sub',
                                                      ('var', 'pred_u'),
                                                      ('var', 'true_u')),
                                                     ('num', 2))])),
                                                 ('body_decl',
                                                  'loss_v',
                                                  'ℝ',
                                                  ('call',
                                                   'mean',
                                                   [('pow',
                                                     ('sub',
                                                      ('var', 'pred_v'),
                                                      ('var', 'true_v')),
                                                     ('num', 2))])),
                                                 ('body_decl',
                                                  'loss_p',
                                                  'ℝ',
                                                  ('call',
                                                   'mean',
                                                   [('pow',
                                                     ('sub',
                                                      ('var', 'pred_p'),
                                                      ('var', 'true_p')),
                                                     ('num', 2))])),
                                                 ('body_decl',
                                                  'loss',
                                                  'ℝ',
                                                  ('add',
                                                   ('add',
                                                    ('var', 'loss_u'),
                                                    ('var', 'loss_v')),
                                                   ('var', 'loss_p')))]},
               'adam': {'params': [('ρ', 'ℝ'),
                                   ('g', 'ℝ'),
                                   ('m', 'ℝ'),
                                   ('v', 'ℝ'),
                                   ('t', 'ℝ'),
                                   ('lr', 'ℝ')],
                        'return_type': ('tensor', [(4, 'invariant')]),
                        'body': ('array',
                                 [('var', 'ρ_new'),
                                  ('var', 'm_new'),
                                  ('var', 'v_new'),
                                  ('add', ('var', 't'), ('num', 1.0))]),
                        'has_loop': False,
                        'statements': [('body_decl', 'β1', 'ℝ', ('num', 0.9)),
                                       ('body_decl', 'β2', 'ℝ', ('num', 0.999)),
                                       ('body_decl', 'ε', 'ℝ', ('num', 1e-08)),
                                       ('body_decl',
                                        'm_new',
                                        'ℝ',
                                        ('add',
                                         ('mul', ('var', 'β1'), ('var', 'm')),
                                         ('mul',
                                          ('sub', ('num', 1.0), ('var', 'β1')),
                                          ('var', 'g')))),
                                       ('body_decl',
                                        'v_new',
                                        'ℝ',
                                        ('add',
                                         ('mul', ('var', 'β2'), ('var', 'v')),
                                         ('mul',
                                          ('sub', ('num', 1.0), ('var', 'β2')),
                                          ('pow', ('var', 'g'), ('num', 2))))),
                                       ('body_decl',
                                        'm_hat',
                                        'ℝ',
                                        ('div',
                                         ('var', 'm_new'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow',
                                           ('var', 'β1'),
                                           ('var', 't'))))),
                                       ('body_decl',
                                        'v_hat',
                                        'ℝ',
                                        ('div',
                                         ('var', 'v_new'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow',
                                           ('var', 'β2'),
                                           ('var', 't'))))),
                                       ('body_decl',
                                        'ρ_new',
                                        'ℝ',
                                        ('sub',
                                         ('var', 'ρ'),
                                         ('div',
                                          ('mul',
                                           ('var', 'lr'),
                                           ('var', 'm_hat')),
                                          ('add',
                                           ('call', 'sqrt', [('var', 'v_hat')]),
                                           ('var', 'ε')))))]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'linspace'),
             ('func_def', 'zero_2d_array'),
             ('decl', 'n_points', 'ℝ', ('num', 21), 26),
             ('decl', 'domain_size', 'ℝ', ('num', 1.0), 27),
             ('decl', 'n_iterations', 'ℝ', ('num', 500), 28),
             ('decl', 'time_step_length', 'ℝ', ('num', 0.001), 30),
             ('decl', 'ν', 'ℝ', ('num', 0.1), 31),
             ('decl', 'true_ρ', 'ℝ', ('num', 1.0), 32),
             ('decl', 'horizontal_velocity_top', 'ℝ', ('num', 1.0), 33),
             ('decl', 'n_pressure_poisson_iterations', 'ℝ', ('num', 10), 35),
             ('decl', 'stability_safety_factor', 'ℝ', ('num', 0.5), 36),
             ('decl',
              'element_length',
              'ℝ',
              ('div',
               ('var', 'domain_size'),
               ('sub', ('var', 'n_points'), ('num', 1))),
              38),
             ('decl',
              'x',
              ('tensor', [('n_points', 'invariant')]),
              ('call',
               'linspace',
               [('num', 0.0), ('var', 'domain_size'), ('var', 'n_points')]),
              40),
             ('decl',
              'y',
              ('tensor', [('n_points', 'invariant')]),
              ('call',
               'linspace',
               [('num', 0.0), ('var', 'domain_size'), ('var', 'n_points')]),
              41),
             ('func_def', 'central_difference_x'),
             ('func_def', 'central_difference_y'),
             ('func_def', 'laplace'),
             ('decl',
              'f',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('call',
               'zero_2d_array',
               [('var', 'n_points'), ('var', 'n_points')]),
              79),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'n_points'),
              [('for_loop_range',
                'j',
                ('num', 0),
                ('var', 'n_points'),
                [('for_assign',
                  't_x',
                  ('mul', ('var', 'j'), ('var', 'element_length'))),
                 ('for_assign',
                  't_y',
                  ('mul', ('imaginary',), ('var', 'element_length'))),
                 ('for_index_assign_nd',
                  'f',
                  [('index_item', ('imaginary',)),
                   ('index_item', ('var', 'j'))],
                  ('add',
                   ('pow', ('var', 't_x'), ('num', 2)),
                   ('pow', ('var', 't_y'), ('num', 2))))],
                82)],
              81),
             ('func_def', 'apply_u_bc'),
             ('func_def', 'apply_v_bc'),
             ('func_def', 'apply_p_bc'),
             ('func_def', 'advect_diffuse'),
             ('func_def', 'solve_pressure'),
             ('decl', 'n_iterations', 'ℝ', ('num', 5), 132),
             ('func_def', 'solver'),
             ('decl',
              'true_solution',
              ('tensor',
               [(3, 'invariant'),
                ('n_points', 'invariant'),
                ('n_points', 'invariant')]),
              ('call', 'solver', [('var', 'true_ρ')]),
              150),
             ('decl',
              'true_u',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('index', 'true_solution', ('num', 0)),
              151),
             ('decl',
              'true_v',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('index', 'true_solution', ('num', 1)),
              152),
             ('decl',
              'true_p',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('index', 'true_solution', ('num', 2)),
              153),
             ('func_def', 'calculate_loss'),
             ('func_def', 'adam'),
             ('decl', 'ρ', 'ℝ', ('num', 3.0), 187),
             ('stmt_tuple_unpack',
              [('m_adam', 'ℝ'), ('v_adam', 'ℝ'), ('t_adam', 'ℝ'), ('lr', 'ℝ')],
              ('expr_list',
               [('num', 0.0), ('num', 0.0), ('num', 1.0), ('num', 0.01)])),
             ('decl', 'epochs', 'ℕ', ('num', 1), 196),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_call', 'print', [('imaginary',)]),
               ('for_assign',
                'g',
                ('call', 'grad', [('var', 'calculate_loss'), ('var', 'ρ')])),
               ('for_assign',
                'result',
                ('call',
                 'adam',
                 [('var', 'ρ'),
                  ('var', 'g'),
                  ('var', 'm_adam'),
                  ('var', 'v_adam'),
                  ('var', 't_adam'),
                  ('var', 'lr')])),
               ('for_assign', 'ρ', ('index', 'result', ('num', 0))),
               ('for_assign', 'm_adam', ('index', 'result', ('num', 1))),
               ('for_assign', 'v_adam', ('index', 'result', ('num', 2))),
               ('for_assign', 't_adam', ('index', 'result', ('num', 3))),
               ('for_call', 'print', [('var', 'ρ')])],
              198),
             ('expr', ('var', 'ρ'), 0),
             ('decl',
              'pred_solution',
              ('tensor',
               [(3, 'invariant'),
                ('n_points', 'invariant'),
                ('n_points', 'invariant')]),
              ('call', 'solver', [('var', 'ρ')]),
              216),
             ('decl',
              'pred_u',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('index', 'pred_solution', ('num', 0)),
              217),
             ('decl',
              'pred_v',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('index', 'pred_solution', ('num', 1)),
              218),
             ('decl',
              'pred_p',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('index', 'pred_solution', ('num', 2)),
              219),
             ('decl',
              'X',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('call',
               'zero_2d_array',
               [('var', 'n_points'), ('var', 'n_points')]),
              222),
             ('decl',
              'Y',
              ('tensor',
               [('n_points', 'invariant'), ('n_points', 'invariant')]),
              ('call',
               'zero_2d_array',
               [('var', 'n_points'), ('var', 'n_points')]),
              223),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'n_points'),
              [('for_loop_range',
                'j',
                ('num', 0),
                ('var', 'n_points'),
                [('for_index_assign_nd',
                  'X',
                  [('index_item', ('imaginary',)),
                   ('index_item', ('var', 'j'))],
                  ('mul', ('var', 'j'), ('var', 'element_length'))),
                 ('for_index_assign_nd',
                  'Y',
                  [('index_item', ('imaginary',)),
                   ('index_item', ('var', 'j'))],
                  ('mul', ('imaginary',), ('var', 'element_length')))],
                226)],
              225)]}
