EXPECTED = {'functions': {'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℕ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℕ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'lu_decomposition': {'params': [('A',
                                                ('tensor',
                                                 [('n', 'invariant'),
                                                  ('n', 'invariant')])),
                                               ('b',
                                                ('tensor',
                                                 [('n', 'invariant')]))],
                                    'return_type': ('tensor',
                                                    [('n', 'invariant')]),
                                    'body': ('var', 'results'),
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'n_size',
                                                    'ℕ',
                                                    ('call',
                                                     'get_2d_array_num_rows',
                                                     [('var', 'A')])),
                                                   ('body_decl',
                                                    'P',
                                                    ('tensor',
                                                     [('n_size', 'invariant'),
                                                      ('n_size', 'invariant')]),
                                                    ('call',
                                                     'zeros',
                                                     [('var', 'n_size'),
                                                      ('var', 'n_size')])),
                                                   ('body_for_range',
                                                    'i',
                                                    ('num', 0),
                                                    ('var', 'n_size'),
                                                    [('loop_index_assign_nd',
                                                      'P',
                                                      [('index_item',
                                                        ('imaginary',)),
                                                       ('index_item',
                                                        ('imaginary',))],
                                                      ('num', 1.0))]),
                                                   ('body_decl',
                                                    'L',
                                                    ('tensor',
                                                     [('n_size', 'invariant'),
                                                      ('n_size', 'invariant')]),
                                                    ('call',
                                                     'zeros',
                                                     [('var', 'n_size'),
                                                      ('var', 'n_size')])),
                                                   ('body_decl',
                                                    'U',
                                                    ('tensor',
                                                     [('n_size', 'invariant'),
                                                      ('n_size', 'invariant')]),
                                                    ('call',
                                                     'zeros',
                                                     [('var', 'n_size'),
                                                      ('var', 'n_size')])),
                                                   ('body_for_range',
                                                    'j',
                                                    ('num', 0),
                                                    ('var', 'n_size'),
                                                    [('loop_assign',
                                                      'max_row',
                                                      ('var', 'j')),
                                                     ('loop_for_range',
                                                      'i',
                                                      ('add',
                                                       ('var', 'j'),
                                                       ('num', 1)),
                                                      ('var', 'n_size'),
                                                      [('loop_if',
                                                        ('cond_gt',
                                                         ('call',
                                                          'abs',
                                                          [('indexN',
                                                            'A',
                                                            [('index_item',
                                                              ('imaginary',)),
                                                             ('index_item',
                                                              ('var', 'j'))])]),
                                                         ('call',
                                                          'abs',
                                                          [('indexN',
                                                            'A',
                                                            [('index_item',
                                                              ('var',
                                                               'max_row')),
                                                             ('index_item',
                                                              ('var',
                                                               'j'))])])),
                                                        [('loop_assign',
                                                          'max_row',
                                                          ('imaginary',))])]),
                                                     ('loop_assign',
                                                      'A_next',
                                                      ('call',
                                                       'zeros',
                                                       [('var', 'n_size'),
                                                        ('var', 'n_size')])),
                                                     ('loop_assign',
                                                      'L_next',
                                                      ('call',
                                                       'zeros',
                                                       [('var', 'n_size'),
                                                        ('var', 'n_size')])),
                                                     ('loop_assign',
                                                      'P_next',
                                                      ('call',
                                                       'zeros',
                                                       [('var', 'n_size'),
                                                        ('var', 'n_size')])),
                                                     ('loop_for_range',
                                                      'r',
                                                      ('num', 0),
                                                      ('var', 'n_size'),
                                                      [('loop_assign',
                                                        'source',
                                                        ('var', 'r')),
                                                       ('loop_if_else',
                                                        ('cond_eq',
                                                         ('var', 'r'),
                                                         ('var', 'j')),
                                                        [('loop_assign',
                                                          'source',
                                                          ('var', 'max_row'))],
                                                        [('loop_if',
                                                          ('cond_eq',
                                                           ('var', 'r'),
                                                           ('var', 'max_row')),
                                                          [('loop_assign',
                                                            'source',
                                                            ('var', 'j'))])]),
                                                       ('loop_for_range',
                                                        'c',
                                                        ('num', 0),
                                                        ('var', 'n_size'),
                                                        [('loop_index_assign_nd',
                                                          'A_next',
                                                          [('index_item',
                                                            ('var', 'r')),
                                                           ('index_item',
                                                            ('var', 'c'))],
                                                          ('indexN',
                                                           'A',
                                                           [('index_item',
                                                             ('var', 'source')),
                                                            ('index_item',
                                                             ('var', 'c'))])),
                                                         ('loop_index_assign_nd',
                                                          'L_next',
                                                          [('index_item',
                                                            ('var', 'r')),
                                                           ('index_item',
                                                            ('var', 'c'))],
                                                          ('indexN',
                                                           'L',
                                                           [('index_item',
                                                             ('var', 'source')),
                                                            ('index_item',
                                                             ('var', 'c'))])),
                                                         ('loop_index_assign_nd',
                                                          'P_next',
                                                          [('index_item',
                                                            ('var', 'r')),
                                                           ('index_item',
                                                            ('var', 'c'))],
                                                          ('indexN',
                                                           'P',
                                                           [('index_item',
                                                             ('var', 'source')),
                                                            ('index_item',
                                                             ('var',
                                                              'c'))]))])]),
                                                     ('loop_assign',
                                                      'A',
                                                      ('var', 'A_next')),
                                                     ('loop_assign',
                                                      'L',
                                                      ('var', 'L_next')),
                                                     ('loop_assign',
                                                      'P',
                                                      ('var', 'P_next')),
                                                     ('loop_assign',
                                                      'u_col',
                                                      ('call',
                                                       'zeros',
                                                       [('var', 'n_size')])),
                                                     ('loop_for_range',
                                                      'i',
                                                      ('num', 0),
                                                      ('add',
                                                       ('var', 'j'),
                                                       ('num', 1)),
                                                      [('loop_assign',
                                                        'partial',
                                                        ('num', 0.0)),
                                                       ('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('imaginary',),
                                                        [('loop_assign',
                                                          'partial',
                                                          ('add',
                                                           ('var', 'partial'),
                                                           ('mul',
                                                            ('index',
                                                             'u_col',
                                                             ('var', 'k')),
                                                            ('indexN',
                                                             'L',
                                                             [('index_item',
                                                               ('imaginary',)),
                                                              ('index_item',
                                                               ('var',
                                                                'k'))]))))]),
                                                       ('loop_assign',
                                                        'new_val',
                                                        ('sub',
                                                         ('indexN',
                                                          'A',
                                                          [('index_item',
                                                            ('imaginary',)),
                                                           ('index_item',
                                                            ('var', 'j'))]),
                                                         ('var', 'partial'))),
                                                       ('loop_assign',
                                                        'u_col_next',
                                                        ('call',
                                                         'zeros',
                                                         [('var', 'n_size')])),
                                                       ('loop_for_range',
                                                        'c',
                                                        ('num', 0),
                                                        ('var', 'n_size'),
                                                        [('loop_if_else',
                                                          ('cond_eq',
                                                           ('var', 'c'),
                                                           ('imaginary',)),
                                                          [('loop_index_assign_nd',
                                                            'u_col_next',
                                                            [('index_item',
                                                              ('var', 'c'))],
                                                            ('var',
                                                             'new_val'))],
                                                          [('loop_index_assign_nd',
                                                            'u_col_next',
                                                            [('index_item',
                                                              ('var', 'c'))],
                                                            ('index',
                                                             'u_col',
                                                             ('var', 'c')))])]),
                                                       ('loop_assign',
                                                        'u_col',
                                                        ('var',
                                                         'u_col_next'))]),
                                                     ('loop_assign',
                                                      'l_col',
                                                      ('call',
                                                       'zeros',
                                                       [('var', 'n_size')])),
                                                     ('loop_for_range',
                                                      'i',
                                                      ('var', 'j'),
                                                      ('var', 'n_size'),
                                                      [('loop_assign',
                                                        'partial',
                                                        ('num', 0.0)),
                                                       ('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('var', 'j'),
                                                        [('loop_assign',
                                                          'partial',
                                                          ('add',
                                                           ('var', 'partial'),
                                                           ('mul',
                                                            ('index',
                                                             'u_col',
                                                             ('var', 'k')),
                                                            ('indexN',
                                                             'L',
                                                             [('index_item',
                                                               ('imaginary',)),
                                                              ('index_item',
                                                               ('var',
                                                                'k'))]))))]),
                                                       ('loop_assign',
                                                        'new_val',
                                                        ('div',
                                                         ('sub',
                                                          ('indexN',
                                                           'A',
                                                           [('index_item',
                                                             ('imaginary',)),
                                                            ('index_item',
                                                             ('var', 'j'))]),
                                                          ('var', 'partial')),
                                                         ('index',
                                                          'u_col',
                                                          ('var', 'j')))),
                                                       ('loop_assign',
                                                        'l_col_next',
                                                        ('call',
                                                         'zeros',
                                                         [('var', 'n_size')])),
                                                       ('loop_for_range',
                                                        'c',
                                                        ('num', 0),
                                                        ('var', 'n_size'),
                                                        [('loop_if_else',
                                                          ('cond_eq',
                                                           ('var', 'c'),
                                                           ('imaginary',)),
                                                          [('loop_index_assign_nd',
                                                            'l_col_next',
                                                            [('index_item',
                                                              ('var', 'c'))],
                                                            ('var',
                                                             'new_val'))],
                                                          [('loop_index_assign_nd',
                                                            'l_col_next',
                                                            [('index_item',
                                                              ('var', 'c'))],
                                                            ('index',
                                                             'l_col',
                                                             ('var', 'c')))])]),
                                                       ('loop_assign',
                                                        'l_col',
                                                        ('var',
                                                         'l_col_next'))]),
                                                     ('loop_assign',
                                                      'U_next',
                                                      ('call',
                                                       'zeros',
                                                       [('var', 'n_size'),
                                                        ('var', 'n_size')])),
                                                     ('loop_assign',
                                                      'L_next2',
                                                      ('call',
                                                       'zeros',
                                                       [('var', 'n_size'),
                                                        ('var', 'n_size')])),
                                                     ('loop_for_range',
                                                      'r',
                                                      ('num', 0),
                                                      ('var', 'n_size'),
                                                      [('loop_for_range',
                                                        'c',
                                                        ('num', 0),
                                                        ('var', 'n_size'),
                                                        [('loop_if_else',
                                                          ('cond_eq',
                                                           ('var', 'c'),
                                                           ('var', 'j')),
                                                          [('loop_index_assign_nd',
                                                            'U_next',
                                                            [('index_item',
                                                              ('var', 'r')),
                                                             ('index_item',
                                                              ('var', 'c'))],
                                                            ('index',
                                                             'u_col',
                                                             ('var', 'r'))),
                                                           ('loop_index_assign_nd',
                                                            'L_next2',
                                                            [('index_item',
                                                              ('var', 'r')),
                                                             ('index_item',
                                                              ('var', 'c'))],
                                                            ('index',
                                                             'l_col',
                                                             ('var', 'r')))],
                                                          [('loop_index_assign_nd',
                                                            'U_next',
                                                            [('index_item',
                                                              ('var', 'r')),
                                                             ('index_item',
                                                              ('var', 'c'))],
                                                            ('indexN',
                                                             'U',
                                                             [('index_item',
                                                               ('var', 'r')),
                                                              ('index_item',
                                                               ('var', 'c'))])),
                                                           ('loop_index_assign_nd',
                                                            'L_next2',
                                                            [('index_item',
                                                              ('var', 'r')),
                                                             ('index_item',
                                                              ('var', 'c'))],
                                                            ('indexN',
                                                             'L',
                                                             [('index_item',
                                                               ('var', 'r')),
                                                              ('index_item',
                                                               ('var',
                                                                'c'))]))])])]),
                                                     ('loop_assign',
                                                      'U',
                                                      ('var', 'U_next')),
                                                     ('loop_assign',
                                                      'L',
                                                      ('var', 'L_next2'))]),
                                                   ('body_decl',
                                                    'Pb',
                                                    ('tensor',
                                                     [('n_size', 'invariant')]),
                                                    ('call',
                                                     'zeros',
                                                     [('var', 'n_size')])),
                                                   ('body_for_range',
                                                    'i',
                                                    ('num', 0),
                                                    ('var', 'n_size'),
                                                    [('loop_assign',
                                                      'sum_val',
                                                      ('num', 0.0)),
                                                     ('loop_for_range',
                                                      'j',
                                                      ('num', 0),
                                                      ('var', 'n_size'),
                                                      [('loop_assign',
                                                        'sum_val',
                                                        ('add',
                                                         ('var', 'sum_val'),
                                                         ('mul',
                                                          ('indexN',
                                                           'P',
                                                           [('index_item',
                                                             ('imaginary',)),
                                                            ('index_item',
                                                             ('var', 'j'))]),
                                                          ('index',
                                                           'b',
                                                           ('var', 'j')))))]),
                                                     ('loop_index_assign_nd',
                                                      'Pb',
                                                      [('index_item',
                                                        ('imaginary',))],
                                                      ('var', 'sum_val'))]),
                                                   ('body_decl',
                                                    'y',
                                                    ('tensor',
                                                     [('n_size', 'invariant')]),
                                                    ('call',
                                                     'zeros',
                                                     [('var', 'n_size')])),
                                                   ('body_for_range',
                                                    'i',
                                                    ('num', 0),
                                                    ('var', 'n_size'),
                                                    [('loop_assign',
                                                      'total',
                                                      ('index',
                                                       'Pb',
                                                       ('imaginary',))),
                                                     ('loop_for_range',
                                                      'j',
                                                      ('num', 0),
                                                      ('imaginary',),
                                                      [('loop_assign',
                                                        'total',
                                                        ('sub',
                                                         ('var', 'total'),
                                                         ('mul',
                                                          ('indexN',
                                                           'L',
                                                           [('index_item',
                                                             ('imaginary',)),
                                                            ('index_item',
                                                             ('var', 'j'))]),
                                                          ('index',
                                                           'y',
                                                           ('var', 'j')))))]),
                                                     ('loop_assign',
                                                      'solved_val',
                                                      ('div',
                                                       ('var', 'total'),
                                                       ('indexN',
                                                        'L',
                                                        [('index_item',
                                                          ('imaginary',)),
                                                         ('index_item',
                                                          ('imaginary',))]))),
                                                     ('loop_assign',
                                                      'y_next',
                                                      ('call',
                                                       'zeros',
                                                       [('var', 'n_size')])),
                                                     ('loop_for_range',
                                                      'c',
                                                      ('num', 0),
                                                      ('var', 'n_size'),
                                                      [('loop_if_else',
                                                        ('cond_eq',
                                                         ('var', 'c'),
                                                         ('imaginary',)),
                                                        [('loop_index_assign_nd',
                                                          'y_next',
                                                          [('index_item',
                                                            ('var', 'c'))],
                                                          ('var',
                                                           'solved_val'))],
                                                        [('loop_index_assign_nd',
                                                          'y_next',
                                                          [('index_item',
                                                            ('var', 'c'))],
                                                          ('index',
                                                           'y',
                                                           ('var', 'c')))])]),
                                                     ('loop_assign',
                                                      'y',
                                                      ('var', 'y_next'))]),
                                                   ('body_decl',
                                                    'results',
                                                    ('tensor',
                                                     [('n_size', 'invariant')]),
                                                    ('call',
                                                     'zeros',
                                                     [('var', 'n_size')])),
                                                   ('body_for_range',
                                                    'i',
                                                    ('num', 0),
                                                    ('var', 'n_size'),
                                                    [('loop_assign',
                                                      'idx',
                                                      ('sub',
                                                       ('sub',
                                                        ('var', 'n_size'),
                                                        ('num', 1)),
                                                       ('imaginary',))),
                                                     ('loop_assign',
                                                      'total',
                                                      ('index',
                                                       'y',
                                                       ('var', 'idx'))),
                                                     ('loop_for_range',
                                                      'j',
                                                      ('add',
                                                       ('var', 'idx'),
                                                       ('num', 1)),
                                                      ('var', 'n_size'),
                                                      [('loop_assign',
                                                        'total',
                                                        ('sub',
                                                         ('var', 'total'),
                                                         ('mul',
                                                          ('indexN',
                                                           'U',
                                                           [('index_item',
                                                             ('var', 'idx')),
                                                            ('index_item',
                                                             ('var', 'j'))]),
                                                          ('index',
                                                           'results',
                                                           ('var', 'j')))))]),
                                                     ('loop_assign',
                                                      'solved_val',
                                                      ('div',
                                                       ('var', 'total'),
                                                       ('indexN',
                                                        'U',
                                                        [('index_item',
                                                          ('var', 'idx')),
                                                         ('index_item',
                                                          ('var', 'idx'))]))),
                                                     ('loop_assign',
                                                      'results_next',
                                                      ('call',
                                                       'zeros',
                                                       [('var', 'n_size')])),
                                                     ('loop_for_range',
                                                      'c',
                                                      ('num', 0),
                                                      ('var', 'n_size'),
                                                      [('loop_if_else',
                                                        ('cond_eq',
                                                         ('var', 'c'),
                                                         ('var', 'idx')),
                                                        [('loop_index_assign_nd',
                                                          'results_next',
                                                          [('index_item',
                                                            ('var', 'c'))],
                                                          ('var',
                                                           'solved_val'))],
                                                        [('loop_index_assign_nd',
                                                          'results_next',
                                                          [('index_item',
                                                            ('var', 'c'))],
                                                          ('index',
                                                           'results',
                                                           ('var', 'c')))])]),
                                                     ('loop_assign',
                                                      'results',
                                                      ('var',
                                                       'results_next'))])]}},
 'classes': {},
 'program': [('func_def', 'get_2d_array_num_rows'),
             ('func_def', 'lu_decomposition'),
             ('decl',
              'A',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('neg', ('num', 1)), ('num', 0), ('num', 3)]),
                ('array', [('num', 2), ('num', 1), ('num', 3)]),
                ('array', [('num', 1), ('num', 1), ('num', 2)])]),
              137),
             ('decl',
              'b',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 1), ('num', 2), ('num', 3)]),
              143),
             ('expr',
              ('call', 'lu_decomposition', [('var', 'A'), ('var', 'b')]),
              0)]}
