EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'get_2d_array_num_cols': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('call',
                                                  'get_1d_array_length',
                                                  [('index', 'x', ('num', 0))]),
                                         'has_loop': False,
                                         'statements': []},
               'arange': {'params': [('n', 'ℕ')],
                          'return_type': ('tensor', [('n', 'invariant')]),
                          'body': ('var', 'arr'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'arr',
                                          ('tensor', [('n', 'invariant')]),
                                          ('for_expr',
                                           'i',
                                           ('var', 'n'),
                                           ('imaginary',)))]},
               'gaussian_solve': {'params': [('A',
                                              ('tensor',
                                               [('m', 'invariant'),
                                                ('n', 'invariant')])),
                                             ('b',
                                              ('tensor',
                                               [('n', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [('m', 'invariant')]),
                                  'body': ('var', 'x'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'a_row',
                                                  'ℝ',
                                                  ('call',
                                                   'get_2d_array_num_rows',
                                                   [('var', 'A')])),
                                                 ('body_decl',
                                                  'a_col',
                                                  'ℝ',
                                                  ('call',
                                                   'get_2d_array_num_cols',
                                                   [('var', 'A')])),
                                                 ('body_decl',
                                                  'new_col',
                                                  'ℝ',
                                                  ('add',
                                                   ('var', 'a_col'),
                                                   ('num', 1))),
                                                 ('body_decl',
                                                  'aug',
                                                  ('tensor',
                                                   [('a_row', 'invariant'),
                                                    ('new_col', 'invariant')]),
                                                  ('call',
                                                   'zero_2d_array',
                                                   [('var', 'a_row'),
                                                    ('var', 'new_col')])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_row'),
                                                  [('loop_for_range',
                                                    'c',
                                                    ('num', 0),
                                                    ('var', 'a_col'),
                                                    [('loop_index_assign_nd',
                                                      'aug',
                                                      [('index_item',
                                                        ('imaginary',)),
                                                       ('index_item',
                                                        ('var', 'c'))],
                                                      ('indexN',
                                                       'A',
                                                       [('index_item',
                                                         ('imaginary',)),
                                                        ('index_item',
                                                         ('var', 'c'))]))]),
                                                   ('loop_index_assign_nd',
                                                    'aug',
                                                    [('index_item',
                                                      ('imaginary',)),
                                                     ('index_item',
                                                      ('var', 'a_col'))],
                                                    ('index',
                                                     'b',
                                                     ('imaginary',)))]),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_row'),
                                                  [('loop_assign',
                                                    'max_row',
                                                    ('imaginary',)),
                                                   ('loop_for_range',
                                                    'k',
                                                    ('add',
                                                     ('imaginary',),
                                                     ('num', 1)),
                                                    ('var', 'a_row'),
                                                    [('loop_if',
                                                      ('cond_gt',
                                                       ('call',
                                                        'abs',
                                                        [('indexN',
                                                          'aug',
                                                          [('index_item',
                                                            ('var', 'k')),
                                                           ('index_item',
                                                            ('imaginary',))])]),
                                                       ('call',
                                                        'abs',
                                                        [('indexN',
                                                          'aug',
                                                          [('index_item',
                                                            ('var', 'max_row')),
                                                           ('index_item',
                                                            ('imaginary',))])])),
                                                      [('loop_assign',
                                                        'max_row',
                                                        ('var', 'k'))])]),
                                                   ('loop_assign',
                                                    'pivot_row',
                                                    ('call',
                                                     'zero_1d_array',
                                                     [('var', 'new_col')])),
                                                   ('loop_assign',
                                                    'displaced_row',
                                                    ('call',
                                                     'zero_1d_array',
                                                     [('var', 'new_col')])),
                                                   ('loop_for_range',
                                                    'c',
                                                    ('num', 0),
                                                    ('var', 'new_col'),
                                                    [('loop_index_assign_nd',
                                                      'pivot_row',
                                                      [('index_item',
                                                        ('var', 'c'))],
                                                      ('indexN',
                                                       'aug',
                                                       [('index_item',
                                                         ('var', 'max_row')),
                                                        ('index_item',
                                                         ('var', 'c'))])),
                                                     ('loop_index_assign_nd',
                                                      'displaced_row',
                                                      [('index_item',
                                                        ('var', 'c'))],
                                                      ('indexN',
                                                       'aug',
                                                       [('index_item',
                                                         ('imaginary',)),
                                                        ('index_item',
                                                         ('var', 'c'))]))]),
                                                   ('loop_assign',
                                                    'aug_next',
                                                    ('call',
                                                     'zero_2d_array',
                                                     [('var', 'a_row'),
                                                      ('var', 'new_col')])),
                                                   ('loop_for_range',
                                                    'row_idx',
                                                    ('num', 0),
                                                    ('var', 'a_row'),
                                                    [('loop_if_else',
                                                      ('cond_lt',
                                                       ('var', 'row_idx'),
                                                       ('imaginary',)),
                                                      [('loop_for_range',
                                                        'c',
                                                        ('num', 0),
                                                        ('var', 'new_col'),
                                                        [('loop_index_assign_nd',
                                                          'aug_next',
                                                          [('index_item',
                                                            ('var', 'row_idx')),
                                                           ('index_item',
                                                            ('var', 'c'))],
                                                          ('indexN',
                                                           'aug',
                                                           [('index_item',
                                                             ('var',
                                                              'row_idx')),
                                                            ('index_item',
                                                             ('var',
                                                              'c'))]))])],
                                                      [('loop_if_else',
                                                        ('cond_eq',
                                                         ('var', 'row_idx'),
                                                         ('imaginary',)),
                                                        [('loop_for_range',
                                                          'c',
                                                          ('num', 0),
                                                          ('var', 'new_col'),
                                                          [('loop_index_assign_nd',
                                                            'aug_next',
                                                            [('index_item',
                                                              ('var',
                                                               'row_idx')),
                                                             ('index_item',
                                                              ('var', 'c'))],
                                                            ('index',
                                                             'pivot_row',
                                                             ('var', 'c')))])],
                                                        [('loop_assign',
                                                          'source_row',
                                                          ('call',
                                                           'zero_1d_array',
                                                           [('var',
                                                             'new_col')])),
                                                         ('loop_if_else',
                                                          ('cond_eq',
                                                           ('var', 'row_idx'),
                                                           ('var', 'max_row')),
                                                          [('loop_for_range',
                                                            'c',
                                                            ('num', 0),
                                                            ('var', 'new_col'),
                                                            [('loop_index_assign_nd',
                                                              'source_row',
                                                              [('index_item',
                                                                ('var', 'c'))],
                                                              ('index',
                                                               'displaced_row',
                                                               ('var',
                                                                'c')))])],
                                                          [('loop_for_range',
                                                            'c',
                                                            ('num', 0),
                                                            ('var', 'new_col'),
                                                            [('loop_index_assign_nd',
                                                              'source_row',
                                                              [('index_item',
                                                                ('var', 'c'))],
                                                              ('indexN',
                                                               'aug',
                                                               [('index_item',
                                                                 ('var',
                                                                  'row_idx')),
                                                                ('index_item',
                                                                 ('var',
                                                                  'c'))]))])]),
                                                         ('loop_assign',
                                                          'factor',
                                                          ('div',
                                                           ('index',
                                                            'source_row',
                                                            ('imaginary',)),
                                                           ('index',
                                                            'pivot_row',
                                                            ('imaginary',)))),
                                                         ('loop_for_range',
                                                          'c',
                                                          ('num', 0),
                                                          ('var', 'new_col'),
                                                          [('loop_index_assign_nd',
                                                            'aug_next',
                                                            [('index_item',
                                                              ('var',
                                                               'row_idx')),
                                                             ('index_item',
                                                              ('var', 'c'))],
                                                            ('sub',
                                                             ('index',
                                                              'source_row',
                                                              ('var', 'c')),
                                                             ('mul',
                                                              ('var', 'factor'),
                                                              ('index',
                                                               'pivot_row',
                                                               ('var',
                                                                'c')))))])])])]),
                                                   ('loop_assign',
                                                    'aug',
                                                    ('var', 'aug_next'))]),
                                                 ('body_decl',
                                                  'x',
                                                  ('tensor',
                                                   [('a_col', 'invariant')]),
                                                  ('call',
                                                   'zero_1d_array',
                                                   [('var', 'a_col')])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_col'),
                                                  [('loop_assign',
                                                    'idx',
                                                    ('sub',
                                                     ('sub',
                                                      ('var', 'a_col'),
                                                      ('num', 1)),
                                                     ('imaginary',))),
                                                   ('loop_assign',
                                                    'total',
                                                    ('indexN',
                                                     'aug',
                                                     [('index_item',
                                                       ('var', 'idx')),
                                                      ('index_item',
                                                       ('var', 'a_col'))])),
                                                   ('loop_for_range',
                                                    'j',
                                                    ('add',
                                                     ('var', 'idx'),
                                                     ('num', 1)),
                                                    ('var', 'a_row'),
                                                    [('loop_assign',
                                                      'total',
                                                      ('sub',
                                                       ('var', 'total'),
                                                       ('mul',
                                                        ('indexN',
                                                         'aug',
                                                         [('index_item',
                                                           ('var', 'idx')),
                                                          ('index_item',
                                                           ('var', 'j'))]),
                                                        ('index',
                                                         'x',
                                                         ('var', 'j')))))]),
                                                   ('loop_assign',
                                                    'solved_val',
                                                    ('div',
                                                     ('var', 'total'),
                                                     ('indexN',
                                                      'aug',
                                                      [('index_item',
                                                        ('var', 'idx')),
                                                       ('index_item',
                                                        ('var', 'idx'))]))),
                                                   ('loop_assign',
                                                    'x_next',
                                                    ('call',
                                                     'zero_1d_array',
                                                     [('var', 'a_col')])),
                                                   ('loop_for_range',
                                                    'c',
                                                    ('num', 0),
                                                    ('var', 'a_col'),
                                                    [('loop_if_else',
                                                      ('cond_eq',
                                                       ('var', 'c'),
                                                       ('var', 'idx')),
                                                      [('loop_index_assign_nd',
                                                        'x_next',
                                                        [('index_item',
                                                          ('var', 'c'))],
                                                        ('var', 'solved_val'))],
                                                      [('loop_index_assign_nd',
                                                        'x_next',
                                                        [('index_item',
                                                          ('var', 'c'))],
                                                        ('index',
                                                         'x',
                                                         ('var', 'c')))])]),
                                                   ('loop_assign',
                                                    'x',
                                                    ('var', 'x_next'))])]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'zero_2d_array'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'get_2d_array_num_rows'),
             ('func_def', 'get_2d_array_num_cols'),
             ('func_def', 'arange'),
             ('func_def', 'gaussian_solve'),
             ('decl',
              'A',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 1)]),
                ('array', [('num', 3), ('num', 1), ('neg', ('num', 1))]),
                ('array', [('num', 2), ('neg', ('num', 1)), ('num', 1)])]),
              118),
             ('decl',
              'b',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 8), ('num', 2), ('num', 3)]),
              123),
             ('expr',
              ('call', 'gaussian_solve', [('var', 'A'), ('var', 'b')]),
              0)]}
