EXPECTED = {'functions': {'calculate_model_energies_eV': {'params': [('energy_spacing_eV',
                                                           'ℝ')],
                                               'return_type': ('tensor',
                                                               [('m',
                                                                 'invariant')]),
                                               'body': ('var',
                                                        'model_energies_eV'),
                                               'has_loop': False,
                                               'statements': [('body_decl',
                                                               'model_energies_eV',
                                                               ('tensor',
                                                                [('N_levels',
                                                                  'invariant')]),
                                                               ('for_expr',
                                                                'n',
                                                                ('var',
                                                                 'N_levels'),
                                                                ('mul',
                                                                 ('var', 'n'),
                                                                 ('num',
                                                                  0.0)))),
                                                              ('body_for_range',
                                                               'n',
                                                               ('num', 0),
                                                               ('var',
                                                                'N_levels'),
                                                               [('loop_index_assign_nd',
                                                                 'model_energies_eV',
                                                                 [('index_item',
                                                                   ('var',
                                                                    'n'))],
                                                                 ('mul',
                                                                  ('var',
                                                                   'energy_spacing_eV'),
                                                                  ('add',
                                                                   ('mul',
                                                                    ('var',
                                                                     'n'),
                                                                    ('num',
                                                                     1.0)),
                                                                   ('num',
                                                                    0.5))))])]},
               'calculate_energy_spacing_loss': {'params': [('energy_spacing_eV',
                                                             'ℝ')],
                                                 'return_type': 'ℝ',
                                                 'body': ('div',
                                                          ('var', 'total_loss'),
                                                          ('mul',
                                                           ('var', 'N_levels'),
                                                           ('num', 1.0))),
                                                 'has_loop': False,
                                                 'statements': [('body_decl',
                                                                 'model_energies_eV',
                                                                 ('tensor',
                                                                  [('N_levels',
                                                                    'invariant')]),
                                                                 ('call',
                                                                  'calculate_model_energies_eV',
                                                                  [('var',
                                                                    'energy_spacing_eV')])),
                                                                ('body_decl',
                                                                 'total_loss',
                                                                 'ℝ',
                                                                 ('num', 0.0)),
                                                                ('body_decl',
                                                                 'energy_error_eV',
                                                                 'ℝ',
                                                                 ('num', 0.0)),
                                                                ('body_for_range',
                                                                 'n',
                                                                 ('num', 0),
                                                                 ('var',
                                                                  'N_levels'),
                                                                 [('loop_assign',
                                                                   'energy_error_eV',
                                                                   ('sub',
                                                                    ('index',
                                                                     'model_energies_eV',
                                                                     ('var',
                                                                      'n')),
                                                                    ('index',
                                                                     'reference_energies_eV',
                                                                     ('var',
                                                                      'n')))),
                                                                  ('loop_assign',
                                                                   'total_loss',
                                                                   ('add',
                                                                    ('var',
                                                                     'total_loss'),
                                                                    ('pow',
                                                                     ('var',
                                                                      'energy_error_eV'),
                                                                     ('num',
                                                                      2))))])]},
               'adam': {'params': [('parameter', 'ℝ'),
                                   ('gradient_value', 'ℝ'),
                                   ('first_moment', 'ℝ'),
                                   ('second_moment', 'ℝ'),
                                   ('step', 'ℝ'),
                                   ('learning_rate', 'ℝ')],
                        'return_type': ('tensor', [(4, 'invariant')]),
                        'body': ('array',
                                 [('var', 'new_parameter'),
                                  ('var', 'new_first_moment'),
                                  ('var', 'new_second_moment'),
                                  ('add', ('var', 'step'), ('num', 1.0))]),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        'beta_1',
                                        'ℝ',
                                        ('num', 0.9)),
                                       ('body_decl',
                                        'beta_2',
                                        'ℝ',
                                        ('num', 0.999)),
                                       ('body_decl',
                                        'epsilon',
                                        'ℝ',
                                        ('num', 1e-06)),
                                       ('body_decl',
                                        'new_first_moment',
                                        'ℝ',
                                        ('add',
                                         ('mul',
                                          ('var', 'beta_1'),
                                          ('var', 'first_moment')),
                                         ('mul',
                                          ('sub',
                                           ('num', 1.0),
                                           ('var', 'beta_1')),
                                          ('var', 'gradient_value')))),
                                       ('body_decl',
                                        'new_second_moment',
                                        'ℝ',
                                        ('add',
                                         ('mul',
                                          ('var', 'beta_2'),
                                          ('var', 'second_moment')),
                                         ('mul',
                                          ('sub',
                                           ('num', 1.0),
                                           ('var', 'beta_2')),
                                          ('pow',
                                           ('var', 'gradient_value'),
                                           ('num', 2))))),
                                       ('body_decl',
                                        'corrected_first_moment',
                                        'ℝ',
                                        ('div',
                                         ('var', 'new_first_moment'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow',
                                           ('var', 'beta_1'),
                                           ('var', 'step'))))),
                                       ('body_decl',
                                        'corrected_second_moment',
                                        'ℝ',
                                        ('div',
                                         ('var', 'new_second_moment'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow',
                                           ('var', 'beta_2'),
                                           ('var', 'step'))))),
                                       ('body_decl',
                                        'new_parameter',
                                        'ℝ',
                                        ('sub',
                                         ('var', 'parameter'),
                                         ('div',
                                          ('mul',
                                           ('var', 'learning_rate'),
                                           ('var', 'corrected_first_moment')),
                                          ('add',
                                           ('call',
                                            'sqrt',
                                            [('var',
                                              'corrected_second_moment')]),
                                           ('var', 'epsilon')))))]}},
 'classes': {},
 'program': [('decl', 'ℏ_SI', 'ℝ', ('num', 1.054571817e-34), 2),
             ('decl',
              'joule_per_electronvolt',
              'ℝ',
              ('num', 1.602176634e-19),
              3),
             ('decl', 'atomic_mass_unit', 'ℝ', ('num', 1.6605390666e-27), 4),
             ('decl', 'π', 'ℝ', ('num', 3.141592653589793), 5),
             ('decl', 'meter_to_angstrom', 'ℝ', ('num', 10000000000.0), 6),
             ('decl', 'carbon_mass_amu', 'ℝ', ('num', 12.0), 9),
             ('decl', 'oxygen_mass_amu', 'ℝ', ('num', 15.99491461957), 10),
             ('decl',
              'reduced_mass_amu',
              'ℝ',
              ('div',
               ('mul', ('var', 'carbon_mass_amu'), ('var', 'oxygen_mass_amu')),
               ('add', ('var', 'carbon_mass_amu'), ('var', 'oxygen_mass_amu'))),
              11),
             ('decl',
              'reduced_mass',
              'ℝ',
              ('mul', ('var', 'reduced_mass_amu'), ('var', 'atomic_mass_unit')),
              12),
             ('decl', 'N_levels', 'ℕ', ('num', 5), 15),
             ('decl',
              'reference_energies_eV',
              ('tensor', [('N_levels', 'invariant')]),
              ('array',
               [('num', 0.134509),
                ('num', 0.403527),
                ('num', 0.672545),
                ('num', 0.941563),
                ('num', 1.210581)]),
              16),
             ('func_def', 'calculate_model_energies_eV'),
             ('func_def', 'calculate_energy_spacing_loss'),
             ('func_def', 'adam'),
             ('decl', 'learned_energy_spacing_eV', 'ℝ', ('num', 0.0), 48),
             ('decl', 'first_moment', 'ℝ', ('num', 0.0), 49),
             ('decl', 'second_moment', 'ℝ', ('num', 0.0), 50),
             ('decl', 'optimizer_step', 'ℝ', ('num', 1.0), 51),
             ('decl', 'learning_rate', 'ℝ', ('num', 0.01), 52),
             ('decl', 'epochs', 'ℕ', ('num', 1), 57),
             ('decl', 'energy_spacing_gradient', 'ℝ', ('num', 0.0), 58),
             ('decl',
              'adam_result',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('var', 'learned_energy_spacing_eV'),
                ('var', 'first_moment'),
                ('var', 'second_moment'),
                ('var', 'optimizer_step')]),
              59),
             ('for_loop_range',
              'epoch',
              ('num', 0),
              ('var', 'epochs'),
              [('for_assign',
                'energy_spacing_gradient',
                ('call',
                 'grad',
                 [('var', 'calculate_energy_spacing_loss'),
                  ('var', 'learned_energy_spacing_eV')])),
               ('for_assign',
                'adam_result',
                ('call',
                 'adam',
                 [('var', 'learned_energy_spacing_eV'),
                  ('var', 'energy_spacing_gradient'),
                  ('var', 'first_moment'),
                  ('var', 'second_moment'),
                  ('var', 'optimizer_step'),
                  ('var', 'learning_rate')])),
               ('for_assign',
                'learned_energy_spacing_eV',
                ('index', 'adam_result', ('num', 0))),
               ('for_assign',
                'first_moment',
                ('index', 'adam_result', ('num', 1))),
               ('for_assign',
                'second_moment',
                ('index', 'adam_result', ('num', 2))),
               ('for_assign',
                'optimizer_step',
                ('index', 'adam_result', ('num', 3)))],
              61),
             ('decl',
              'learned_angular_frequency',
              'ℝ',
              ('div',
               ('mul',
                ('var', 'learned_energy_spacing_eV'),
                ('var', 'joule_per_electronvolt')),
               ('var', 'ℏ_SI')),
              70),
             ('decl',
              'learned_force_constant',
              'ℝ',
              ('mul',
               ('var', 'reduced_mass'),
               ('pow', ('var', 'learned_angular_frequency'), ('num', 2))),
              71),
             ('decl',
              'oscillator_length_m',
              'ℝ',
              ('call',
               'sqrt',
               [('div',
                 ('var', 'ℏ_SI'),
                 ('mul',
                  ('var', 'reduced_mass'),
                  ('var', 'learned_angular_frequency')))]),
              74),
             ('decl',
              'x_max_m',
              'ℝ',
              ('mul', ('num', 10.0), ('var', 'oscillator_length_m')),
              77),
             ('decl', 'N_grid', 'ℕ', ('num', 601), 78),
             ('decl',
              'dx_m',
              'ℝ',
              ('div',
               ('mul', ('num', 2.0), ('var', 'x_max_m')),
               ('mul', ('sub', ('var', 'N_grid'), ('num', 1)), ('num', 1.0))),
              79),
             ('decl',
              'position_m',
              ('tensor', [('N_grid', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'N_grid'),
               ('add',
                ('neg', ('var', 'x_max_m')),
                ('mul', ('imaginary',), ('var', 'dx_m')))),
              80),
             ('decl',
              'position_A',
              ('tensor', [('N_grid', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'N_grid'),
               ('mul',
                ('index', 'position_m', ('imaginary',)),
                ('var', 'meter_to_angstrom'))),
              81),
             ('decl',
              'wavefunctions',
              ('tensor', [('N_levels', 'invariant'), ('N_grid', 'invariant')]),
              ('for_expr',
               'n',
               ('var', 'N_levels'),
               ('for_expr',
                'i',
                ('var', 'N_grid'),
                ('mul', ('add', ('var', 'n'), ('imaginary',)), ('num', 0.0)))),
              84),
             ('decl',
              'mass_frequency_over_hbar',
              'ℝ',
              ('div',
               ('mul',
                ('var', 'reduced_mass'),
                ('var', 'learned_angular_frequency')),
               ('var', 'ℏ_SI')),
              87),
             ('decl',
              'normalization_constant',
              'ℝ',
              ('pow',
               ('div', ('var', 'mass_frequency_over_hbar'), ('var', 'π')),
               ('num', 0.25)),
              88),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'N_grid'),
              [('for_index_assign_nd',
                'wavefunctions',
                [('index_item', ('num', 0)), ('index_item', ('imaginary',))],
                ('mul',
                 ('var', 'normalization_constant'),
                 ('call',
                  'exp',
                  [('mul',
                    ('mul',
                     ('neg', ('num', 0.5)),
                     ('var', 'mass_frequency_over_hbar')),
                    ('pow',
                     ('index', 'position_m', ('imaginary',)),
                     ('num', 2)))])))],
              90),
             ('decl', 'one_level', 'ℕ', ('num', 1), 93),
             ('if_only',
              ('cond_gt', ('var', 'N_levels'), ('var', 'one_level')),
              [('for_loop_range',
                'i',
                ('num', 0),
                ('var', 'N_grid'),
                [('for_index_assign_nd',
                  'wavefunctions',
                  [('index_item', ('num', 1)), ('index_item', ('imaginary',))],
                  ('mul',
                   ('mul',
                    ('call',
                     'sqrt',
                     [('mul',
                       ('num', 2.0),
                       ('var', 'mass_frequency_over_hbar'))]),
                    ('index', 'position_m', ('imaginary',))),
                   ('indexN',
                    'wavefunctions',
                    [('index_item', ('num', 0)),
                     ('index_item', ('imaginary',))])))],
                95)]),
             ('decl', 'two_levels', 'ℕ', ('num', 2), 98),
             ('decl', 'n_real', 'ℝ', ('num', 0.0), 99),
             ('decl', 'next_n_real', 'ℝ', ('num', 0.0), 100),
             ('decl', 'first_coefficient', 'ℝ', ('num', 0.0), 101),
             ('decl', 'second_coefficient', 'ℝ', ('num', 0.0), 102),
             ('if_only',
              ('cond_gt', ('var', 'N_levels'), ('var', 'two_levels')),
              [('for_loop_range',
                'n',
                ('num', 1),
                ('sub', ('var', 'N_levels'), ('num', 1)),
                [('for_assign', 'n_real', ('mul', ('var', 'n'), ('num', 1.0))),
                 ('for_assign',
                  'next_n_real',
                  ('add', ('var', 'n_real'), ('num', 1.0))),
                 ('for_assign',
                  'first_coefficient',
                  ('call',
                   'sqrt',
                   [('div', ('num', 2.0), ('var', 'next_n_real'))])),
                 ('for_assign',
                  'second_coefficient',
                  ('call',
                   'sqrt',
                   [('div', ('var', 'n_real'), ('var', 'next_n_real'))])),
                 ('for_loop_range',
                  'i',
                  ('num', 0),
                  ('var', 'N_grid'),
                  [('for_index_assign_nd',
                    'wavefunctions',
                    [('index_item', ('add', ('var', 'n'), ('num', 1))),
                     ('index_item', ('imaginary',))],
                    ('sub',
                     ('mul',
                      ('mul',
                       ('mul',
                        ('var', 'first_coefficient'),
                        ('call',
                         'sqrt',
                         [('var', 'mass_frequency_over_hbar')])),
                       ('index', 'position_m', ('imaginary',))),
                      ('indexN',
                       'wavefunctions',
                       [('index_item', ('var', 'n')),
                        ('index_item', ('imaginary',))])),
                     ('mul',
                      ('var', 'second_coefficient'),
                      ('indexN',
                       'wavefunctions',
                       [('index_item', ('sub', ('var', 'n'), ('num', 1))),
                        ('index_item', ('imaginary',))]))))],
                  110)],
                105)]),
             ('decl',
              'kinetic_coefficient_J_m2',
              'ℝ',
              ('div',
               ('pow', ('var', 'ℏ_SI'), ('num', 2)),
               ('mul', ('num', 2.0), ('var', 'reduced_mass'))),
              114),
             ('decl', 'second_derivative', 'ℝ', ('num', 0.0), 115),
             ('decl',
              'hamiltonian_wavefunctions',
              ('tensor', [('N_levels', 'invariant'), ('N_grid', 'invariant')]),
              ('for_expr',
               'n',
               ('var', 'N_levels'),
               ('for_expr',
                'i',
                ('var', 'N_grid'),
                ('mul', ('add', ('var', 'n'), ('imaginary',)), ('num', 0.0)))),
              116),
             ('decl', 'kinetic_part_J', 'ℝ', ('num', 0.0), 117),
             ('decl', 'potential_part_J', 'ℝ', ('num', 0.0), 118),
             ('decl',
              'potential_J',
              ('tensor', [('N_grid', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'N_grid'),
               ('mul',
                ('mul',
                 ('mul', ('num', 0.5), ('var', 'reduced_mass')),
                 ('pow', ('var', 'learned_angular_frequency'), ('num', 2))),
                ('pow', ('index', 'position_m', ('imaginary',)), ('num', 2)))),
              119),
             ('decl',
              'potential_eV',
              ('tensor', [('N_grid', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'N_grid'),
               ('div',
                ('index', 'potential_J', ('imaginary',)),
                ('var', 'joule_per_electronvolt'))),
              120),
             ('for_loop_range',
              'n',
              ('num', 0),
              ('var', 'N_levels'),
              [('for_loop_range',
                'i',
                ('num', 1),
                ('sub', ('var', 'N_grid'), ('num', 1)),
                [('for_assign',
                  'second_derivative',
                  ('div',
                   ('add',
                    ('sub',
                     ('indexN',
                      'wavefunctions',
                      [('index_item', ('var', 'n')),
                       ('index_item', ('add', ('imaginary',), ('num', 1)))]),
                     ('mul',
                      ('num', 2.0),
                      ('indexN',
                       'wavefunctions',
                       [('index_item', ('var', 'n')),
                        ('index_item', ('imaginary',))]))),
                    ('indexN',
                     'wavefunctions',
                     [('index_item', ('var', 'n')),
                      ('index_item', ('sub', ('imaginary',), ('num', 1)))])),
                   ('mul', ('var', 'dx_m'), ('var', 'dx_m')))),
                 ('for_assign',
                  'kinetic_part_J',
                  ('mul',
                   ('neg', ('var', 'kinetic_coefficient_J_m2')),
                   ('var', 'second_derivative'))),
                 ('for_assign',
                  'potential_part_J',
                  ('mul',
                   ('index', 'potential_J', ('imaginary',)),
                   ('indexN',
                    'wavefunctions',
                    [('index_item', ('var', 'n')),
                     ('index_item', ('imaginary',))]))),
                 ('for_index_assign_nd',
                  'hamiltonian_wavefunctions',
                  [('index_item', ('var', 'n')),
                   ('index_item', ('imaginary',))],
                  ('div',
                   ('add',
                    ('var', 'kinetic_part_J'),
                    ('var', 'potential_part_J')),
                   ('var', 'joule_per_electronvolt')))],
                124)],
              123),
             ('decl', 'energy_numerator', 'ℝ', ('num', 0.0), 131),
             ('decl', 'normalization_integral', 'ℝ', ('num', 0.0), 132),
             ('decl',
              'numerical_energies_eV',
              ('tensor', [('N_levels', 'invariant')]),
              ('for_expr',
               'n',
               ('var', 'N_levels'),
               ('mul', ('var', 'n'), ('num', 0.0))),
              133),
             ('for_loop_range',
              'n',
              ('num', 0),
              ('var', 'N_levels'),
              [('for_assign', 'energy_numerator', ('num', 0.0)),
               ('for_assign', 'normalization_integral', ('num', 0.0)),
               ('for_loop_range',
                'i',
                ('num', 1),
                ('sub', ('var', 'N_grid'), ('num', 1)),
                [('for_assign',
                  'energy_numerator',
                  ('add',
                   ('var', 'energy_numerator'),
                   ('mul',
                    ('mul',
                     ('indexN',
                      'wavefunctions',
                      [('index_item', ('var', 'n')),
                       ('index_item', ('imaginary',))]),
                     ('indexN',
                      'hamiltonian_wavefunctions',
                      [('index_item', ('var', 'n')),
                       ('index_item', ('imaginary',))])),
                    ('var', 'dx_m')))),
                 ('for_assign',
                  'normalization_integral',
                  ('add',
                   ('var', 'normalization_integral'),
                   ('mul',
                    ('mul',
                     ('indexN',
                      'wavefunctions',
                      [('index_item', ('var', 'n')),
                       ('index_item', ('imaginary',))]),
                     ('indexN',
                      'wavefunctions',
                      [('index_item', ('var', 'n')),
                       ('index_item', ('imaginary',))])),
                    ('var', 'dx_m'))))],
                138),
               ('for_index_assign_nd',
                'numerical_energies_eV',
                [('index_item', ('var', 'n'))],
                ('div',
                 ('var', 'energy_numerator'),
                 ('var', 'normalization_integral')))],
              135),
             ('expr',
              ('call', 'print', [('var', 'learned_energy_spacing_eV')]),
              0),
             ('expr',
              ('call', 'print', [('var', 'learned_angular_frequency')]),
              0),
             ('expr',
              ('call', 'print', [('var', 'learned_force_constant')]),
              0)]}
