EXPECTED = {'functions': {'get_sum_of_1d_array': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_pluseq',
                                                         'total',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',)))],
                                                       ['x'])]},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'empty_graph': {'params': [('n_vertices', 'ℕ')],
                               'return_type': ('struct_type',
                                               'UndirectedGraph'),
                               'body': ('var', 'g'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'z',
                                               ('tensor',
                                                [('n_vertices', 'invariant'),
                                                 ('n_vertices', 'invariant')]),
                                               ('for_expr',
                                                'a',
                                                ('var', 'n_vertices'),
                                                ('for_expr',
                                                 'b',
                                                 ('var', 'n_vertices'),
                                                 ('mul',
                                                  ('add',
                                                   ('var', 'a'),
                                                   ('var', 'b')),
                                                  ('num', 0.0))))),
                                              ('body_decl',
                                               'g',
                                               ('struct_type',
                                                'UndirectedGraph'),
                                               ('call',
                                                'UndirectedGraph',
                                                [])),
                                              ('body_field_assign',
                                               ('var', 'g'),
                                               'adjacency',
                                               ('var', 'z'))]}},
 'classes': {'UndirectedGraph': {'class_params': [],
                                 'fields': [('adjacency',
                                             ('tensor',
                                              [('n', 'invariant'),
                                               ('n', 'invariant')]))],
                                 'methods': [{'name': 'num_vertices',
                                              'params': [],
                                              'return_type': 'ℝ',
                                              'statements': [],
                                              'body': ('mul',
                                                       ('call',
                                                        'get_2d_array_num_rows',
                                                        [('field_access',
                                                          ('var', 'this'),
                                                          'adjacency')]),
                                                       ('num', 1.0))},
                                             {'name': 'has_edge',
                                              'params': [('u', 'ℝ'),
                                                         ('v', 'ℝ')],
                                              'return_type': 'ℝ',
                                              'statements': [('body_decl',
                                                              'm',
                                                              ('tensor',
                                                               [('n',
                                                                 'invariant'),
                                                                ('n',
                                                                 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency')),
                                                             ('body_decl',
                                                              'r',
                                                              ('tensor',
                                                               [('n',
                                                                 'invariant')]),
                                                              ('index',
                                                               'm',
                                                               ('var', 'u')))],
                                              'body': ('index',
                                                       'r',
                                                       ('var', 'v'))},
                                             {'name': 'degree',
                                              'params': [('u', 'ℝ')],
                                              'return_type': 'ℝ',
                                              'statements': [('body_decl',
                                                              'm',
                                                              ('tensor',
                                                               [('n',
                                                                 'invariant'),
                                                                ('n',
                                                                 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency')),
                                                             ('body_decl',
                                                              'r',
                                                              ('tensor',
                                                               [('n',
                                                                 'invariant')]),
                                                              ('index',
                                                               'm',
                                                               ('var', 'u')))],
                                              'body': ('call',
                                                       'get_sum_of_1d_array',
                                                       [('var', 'r')])},
                                             {'name': 'sq_degree_sum',
                                              'params': [('s', 'ℝ')],
                                              'return_type': 'ℝ',
                                              'statements': [('body_decl',
                                                              'm',
                                                              ('tensor',
                                                               [('n',
                                                                 'invariant'),
                                                                ('n',
                                                                 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency')),
                                                             ('body_decl',
                                                              'k',
                                                              'ℝ',
                                                              ('call',
                                                               'get_2d_array_num_rows',
                                                               [('var',
                                                                 'm')])),
                                                             ('body_decl',
                                                              'acc',
                                                              'ℝ',
                                                              ('num', 0)),
                                                             ('body_for_range',
                                                              'i',
                                                              ('num', 0),
                                                              ('var', 'k'),
                                                              [('loop_tuple_unpack',
                                                                [('d', 'ℝ')],
                                                                ('num', 0)),
                                                               ('loop_for_range',
                                                                'j',
                                                                ('num', 0),
                                                                ('var', 'k'),
                                                                [('loop_pluseq',
                                                                  'd',
                                                                  ('mul',
                                                                   ('var',
                                                                    's'),
                                                                   ('indexN',
                                                                    'm',
                                                                    [('index_item',
                                                                      ('imaginary',)),
                                                                     ('index_item',
                                                                      ('var',
                                                                       'j'))])))]),
                                                               ('loop_pluseq',
                                                                'acc',
                                                                ('mul',
                                                                 ('var', 'd'),
                                                                 ('var',
                                                                  'd')))])],
                                              'body': ('var', 'acc')},
                                             {'name': 'neighbors',
                                              'params': [('u', 'ℝ')],
                                              'return_type': ('tensor',
                                                              [('n',
                                                                'invariant')]),
                                              'statements': [('body_decl',
                                                              'm',
                                                              ('tensor',
                                                               [('n',
                                                                 'invariant'),
                                                                ('n',
                                                                 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency'))],
                                              'body': ('index',
                                                       'm',
                                                       ('var', 'u'))},
                                             {'name': 'add_weighted_edge',
                                              'params': [('u', 'ℝ'),
                                                         ('v', 'ℝ'),
                                                         ('w', 'ℝ')],
                                              'return_type': None,
                                              'statements': [('body_decl',
                                                              'm',
                                                              ('tensor',
                                                               [('n',
                                                                 'invariant'),
                                                                ('n',
                                                                 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency')),
                                                             ('body_decl',
                                                              'k',
                                                              'ℝ',
                                                              ('call',
                                                               'get_2d_array_num_rows',
                                                               [('var',
                                                                 'm')])),
                                                             ('body_decl',
                                                              'new_adj',
                                                              ('tensor',
                                                               [('n',
                                                                 'invariant'),
                                                                ('n',
                                                                 'invariant')]),
                                                              ('for_expr',
                                                               'a',
                                                               ('var', 'k'),
                                                               ('for_expr',
                                                                'b',
                                                                ('var', 'k'),
                                                                ('indexN',
                                                                 'm',
                                                                 [('index_item',
                                                                   ('var',
                                                                    'a')),
                                                                  ('index_item',
                                                                   ('var',
                                                                    'b'))])))),
                                                             ('body_index_assign_nd',
                                                              'new_adj',
                                                              [('index_item',
                                                                ('var', 'u')),
                                                               ('index_item',
                                                                ('var', 'v'))],
                                                              ('var', 'w')),
                                                             ('body_index_assign_nd',
                                                              'new_adj',
                                                              [('index_item',
                                                                ('var', 'v')),
                                                               ('index_item',
                                                                ('var', 'u'))],
                                                              ('var', 'w')),
                                                             ('body_field_assign',
                                                              ('var', 'this'),
                                                              'adjacency',
                                                              ('var',
                                                               'new_adj'))],
                                              'body': None},
                                             {'name': 'add_edge',
                                              'params': [('u', 'ℝ'),
                                                         ('v', 'ℝ')],
                                              'return_type': None,
                                              'statements': [('body_expr',
                                                              ('method_call',
                                                               ('var', 'this'),
                                                               'add_weighted_edge',
                                                               [('var', 'u'),
                                                                ('var', 'v'),
                                                                ('num',
                                                                 1.0)]))],
                                              'body': None},
                                             {'name': 'grow_adjacency',
                                              'params': [('new_n', 'ℕ')],
                                              'return_type': ('tensor',
                                                              [('new_n',
                                                                'invariant'),
                                                               ('new_n',
                                                                'invariant')]),
                                              'statements': [('body_decl',
                                                              'old',
                                                              ('tensor',
                                                               [('n',
                                                                 'invariant'),
                                                                ('n',
                                                                 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency')),
                                                             ('body_decl',
                                                              'result',
                                                              ('tensor',
                                                               [('new_n',
                                                                 'invariant'),
                                                                ('new_n',
                                                                 'invariant')]),
                                                              ('for_expr',
                                                               'a',
                                                               ('var',
                                                                'new_n'),
                                                               ('for_expr',
                                                                'b',
                                                                ('var',
                                                                 'new_n'),
                                                                ('mul',
                                                                 ('add',
                                                                  ('var', 'a'),
                                                                  ('var',
                                                                   'b')),
                                                                 ('num',
                                                                  0.0))))),
                                                             ('body_decl',
                                                              'm',
                                                              'ℝ',
                                                              ('call',
                                                               'get_2d_array_num_rows',
                                                               [('var',
                                                                 'old')])),
                                                             ('body_for_range',
                                                              'a',
                                                              ('num', 0),
                                                              ('var', 'm'),
                                                              [('loop_for_range',
                                                                'b',
                                                                ('num', 0),
                                                                ('var', 'm'),
                                                                [('loop_index_assign_nd',
                                                                  'result',
                                                                  [('index_item',
                                                                    ('var',
                                                                     'a')),
                                                                   ('index_item',
                                                                    ('var',
                                                                     'b'))],
                                                                  ('indexN',
                                                                   'old',
                                                                   [('index_item',
                                                                     ('var',
                                                                      'a')),
                                                                    ('index_item',
                                                                     ('var',
                                                                      'b'))]))])])],
                                              'body': ('var', 'result')},
                                             {'name': 'add_vertex',
                                              'params': [('new_n', 'ℕ')],
                                              'return_type': None,
                                              'statements': [('body_field_assign',
                                                              ('var', 'this'),
                                                              'adjacency',
                                                              ('method_call',
                                                               ('var', 'this'),
                                                               'grow_adjacency',
                                                               [('var',
                                                                 'new_n')]))],
                                              'body': None}]}},
 'program': [('func_def', 'get_sum_of_1d_array'),
             ('func_def', 'get_2d_array_num_rows'),
             ('class_def', 'UndirectedGraph'),
             ('func_def', 'empty_graph'),
             ('decl', 'n0', 'ℕ', ('num', 3), 66),
             ('decl',
              'g',
              ('struct_type', 'UndirectedGraph'),
              ('call', 'empty_graph', [('var', 'n0')]),
              67),
             ('expr', ('method_call', ('var', 'g'), 'num_vertices', []), 0),
             ('expr',
              ('method_call',
               ('var', 'g'),
               'add_edge',
               [('num', 0.0), ('num', 1.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'g'),
               'add_edge',
               [('num', 1.0), ('num', 2.0)]),
              0),
             ('expr',
              ('method_call', ('var', 'g'), 'neighbors', [('num', 1.0)]),
              0),
             ('expr',
              ('method_call', ('var', 'g'), 'degree', [('num', 1.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'g'),
               'has_edge',
               [('num', 0.0), ('num', 2.0)]),
              0),
             ('decl', 'n3', 'ℕ', ('num', 4), 77),
             ('expr',
              ('method_call', ('var', 'g'), 'add_vertex', [('var', 'n3')]),
              0),
             ('expr',
              ('method_call',
               ('var', 'g'),
               'add_edge',
               [('num', 2.0), ('num', 3.0)]),
              0),
             ('expr',
              ('method_call', ('var', 'g'), 'degree', [('num', 3.0)]),
              0),
             ('decl',
              'wg',
              ('struct_type', 'UndirectedGraph'),
              ('call', 'empty_graph', [('num', 3)]),
              82),
             ('expr',
              ('method_call',
               ('var', 'wg'),
               'add_weighted_edge',
               [('num', 0.0), ('num', 1.0), ('num', 2.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'wg'),
               'add_weighted_edge',
               [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              0),
             ('decl', 's0', 'ℝ', ('num', 1.0), 86),
             ('expr',
              ('method_call', ('var', 'wg'), 'sq_degree_sum', [('var', 's0')]),
              0),
             ('expr',
              ('call',
               'grad',
               [('method_call',
                 ('var', 'wg'),
                 'sq_degree_sum',
                 [('var', 's0')]),
                ('var', 's0')]),
              0)]}
